//
//  HDEEnums.h
//  ie3D-Demo
//
//  Created by sergey.sergeev on 8/12/14.
//  Copyright (c) 2014 Sergey Sergeev. All rights reserved.
//

#ifndef HDEEnums_h
#define HDEEnums_h

enum E_NAVIGATION_MOVE
{
    E_NAVIGATION_MOVE_NONE = 0,
    E_NAVIGATION_MOVE_FORWARD,
    E_NAVIGATION_MOVE_BACKWARD,
    E_NAVIGATION_MOVE_LEFT,
    E_NAVIGATION_MOVE_RIGHT
};

enum E_NAVIGATION_STEER
{
    E_NAVIGATION_STEER_NONE = 0,
    E_NAVIGATION_STEER_LEFT,
    E_NAVIGATION_STEER_RIGHT
};

enum E_CHARACTER_CONTROLLER_MOVE_STATE
{
    E_CHARACTER_CONTROLLER_MOVE_STATE_NONE = 0,
    E_CHARACTER_CONTROLLER_MOVE_STATE_FORWARD,
    E_CHARACTER_CONTROLLER_MOVE_STATE_BACKWARD
};

enum E_CHARACTER_CONTROLLER_STEER_STATE
{
    E_CHARACTER_CONTROLLER_STEER_STATE_NONE = 0,
    E_CHARACTER_CONTROLLER_STEER_STATE_LEFT,
    E_CHARACTER_CONTROLLER_STEER_STATE_RIGHT
};

#endif
