//
//  HKOTHEnums.h
//  indie2dEngine
//
//  Created by Sergey Sergeev on 7/23/13.
//  Copyright (c) 2013 Sergey Sergeev. All rights reserved.
//

#ifndef HKOTHEnums_h
#define HKOTHEnums_h

enum E_MOVE_CONTROLLER_DIRECTION
{
    E_MOVE_CONTROLLER_DIRECTION_NONE = 0,
    E_MOVE_CONTROLLER_DIRECTION_NORTH,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH,
    E_MOVE_CONTROLLER_DIRECTION_WEST,
    E_MOVE_CONTROLLER_DIRECTION_EAST,
    E_MOVE_CONTROLLER_DIRECTION_NORTH_EAST,
    E_MOVE_CONTROLLER_DIRECTION_NORTH_WEST,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH_EAST,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH_WEST
};

enum E_ROTATE_CONTROLLER_DIRECTION
{
    E_ROTATE_CONTROLLER_DIRECTION_NONE = 0,
    E_ROTATE_CONTROLLER_DIRECTION_LEFT,
    E_ROTATE_CONTROLLER_DIRECTION_RIGHT
};

#endif
