// autogenerated: do not add any changes
std::string CConfigurationMaterial::getTechniqueName(void) const
{
const auto& iterator = m_attributes.find("/material/technique_name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial::isDepthTest(void) const
{
const auto& iterator = m_attributes.find("/material/is_depth_test");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial::isDepthMask(void) const
{
const auto& iterator = m_attributes.find("/material/is_depth_mask");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
std::shared_ptr<CConfigurationShader> CConfigurationMaterial::getConfigurationShader(void) const
{
const auto& iterator = m_configurations.find("/material/shader");
assert(iterator != m_configurations.end());
assert(iterator->second.size() != 0;
return std::static_pointer_cast<CConfigurationShader>(iterator->second.at(0));
}
std::vector<std::shared_ptr<CConfigurationTexture>> CConfigurationMaterial::getConfigurationsTextures(void) const
{
const auto& iterator = m_configurations.find("/material/textures/texture");
assert(iterator != m_configurations.end());
return iterator->second;
}
