// autogenerated: do not add any changes
std::string CConfigurationMaterial::getTechniqueName(void) const
{
const auto& iterator = m_attributes.find("/material/technique_name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial::isDepthTest(void) const
{
const auto& iterator = m_attributes.find("/material/is_depth_test");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial::isDepthMask(void) const
{
const auto& iterator = m_attributes.find("/material/is_depth_mask");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
std::shared_ptr<CConfigurationShader> CConfigurationMaterial::getConfigurationShader(void) const
{
}
