// autogenerated: do not add any changes
std::string CConfigurationShader getVsFilename(void) const
{
const auto& iterator = m_attributes.find("/shadervs_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value
}
std::string CConfigurationShader getFsFilename(void) const
{
const auto& iterator = m_attributes.find("/shaderfs_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value
}
