// autogenerated: do not add any changes
std::string CConfigurationMaterial getTechniqueName(void) const
{
const auto& iterator = m_attributes.find("/materialtechnique_name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial getIsDepthTest(void) const
{
const auto& iterator = m_attributes.find("/materialis_depth_test");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
bool CConfigurationMaterial getIsDepthMask(void) const
{
const auto& iterator = m_attributes.find("/materialis_depth_mask");
assert(iterator != m_attributes.end());
bool value; iterator->second->get(&value);
return value
}
