// autogenerated: do not add any changes
#ifndef CConfigurationShader_h
#define CConfigurationShader_h
class CConfigurationShader : public IConfiguration
{
public:
CConfigurationShader(void) = default
~CConfigurationShader(void) = default
std::string getVsFilename(void) const;
std::string getFsFilename(void) const;
};
