// autogenerated: do not add any changes
#ifndef CConfigurationTransition_h
#define CConfigurationTransition_h
#include "IConfiguration.h"
#include "CConfigurationOutputTechnique.h"
#include "CConfigurationWSTechnique.h"
#include "CConfigurationSSTechnique.h"
class CConfigurationTransition : public IConfiguration
{
public:
CConfigurationTransition(void) = default;
~CConfigurationTransition(void) = default;
std::string getGUID(void) const;
#if defined(__EDITOR__)
void setGUID(std::string guid);
#endif
std::shared_ptr<CConfigurationOutputTechnique> getConfigurationOutputTechnique(void) const;
#if defined(__EDITOR__)
void setConfigurationOutputTechnique(const std::shared_ptr<CConfigurationOutputTechnique>& output_technique);
#endif
std::vector<std::shared_ptr<IConfiguration>> getConfigurationWSTechnique(void) const;
#if defined(__EDITOR__)
void addConfigurationWSTechnique(const std::shared_ptr<CConfigurationWSTechnique>& ws_technique);
#endif
#if defined(__EDITOR__)
void setConfigurationWSTechnique(const std::shared_ptr<CConfigurationWSTechnique>& ws_technique, i32 index);
#endif
std::vector<std::shared_ptr<IConfiguration>> getConfigurationSSTechnique(void) const;
#if defined(__EDITOR__)
void addConfigurationSSTechnique(const std::shared_ptr<CConfigurationSSTechnique>& ss_technique);
#endif
#if defined(__EDITOR__)
void setConfigurationSSTechnique(const std::shared_ptr<CConfigurationSSTechnique>& ss_technique, i32 index);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
