// autogenerated: do not add any changes
#ifndef CConfigurationWSTechnique_h
#define CConfigurationWSTechnique_h
#include "IConfiguration.h"
class CConfigurationWSTechnique : public IConfiguration
{
public:
CConfigurationWSTechnique(void) = default;
~CConfigurationWSTechnique(void) = default;
std::string getGUID(void) const;
#if defined(__EDITOR__)
void setGUID(std::string guid);
#endif
bool getDrawBoundingBoxes(void) const;
#if defined(__EDITOR__)
void setDrawBoundingBoxes(bool are_draw_bounding_boxes);
#endif
ui32 getIndex(void) const;
#if defined(__EDITOR__)
void setIndex(ui32 index);
#endif
ui32 getScreenWidth(void) const;
#if defined(__EDITOR__)
void setScreenWidth(ui32 screen_width);
#endif
ui32 getScreenHeight(void) const;
#if defined(__EDITOR__)
void setScreenHeight(ui32 screen_height);
#endif
f32 getClearColorR(void) const;
#if defined(__EDITOR__)
void setClearColorR(f32 clear_color_r);
#endif
f32 getClearColorG(void) const;
#if defined(__EDITOR__)
void setClearColorG(f32 clear_color_g);
#endif
f32 getClearColorB(void) const;
#if defined(__EDITOR__)
void setClearColorB(f32 clear_color_b);
#endif
f32 getClearColorA(void) const;
#if defined(__EDITOR__)
void setClearColorA(f32 clear_color_a);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
