// autogenerated: do not add any changes
#ifndef CConfigurationOcean_h
#define CConfigurationOcean_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationOcean : public IConfigurationGameObject
{
public:
CConfigurationOcean(void) = default;
~CConfigurationOcean(void) = default;
ui32 getSize(void) const;
#if defined(__EDITOR__)
void setSize(ui32 size);
#endif
f32 getAltitude(void) const;
#if defined(__EDITOR__)
void setAltitude(f32 altitude);
#endif
f32 getWaveGenerationInterval(void) const;
#if defined(__EDITOR__)
void setWaveGenerationInterval(f32 wave_generation_interval);
#endif
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
#if defined(__EDITOR__)
void addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material);
#endif
#if defined(__EDITOR__)
void setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
