// autogenerated: do not add any changes
#ifndef CConfigurationShader_h
#define CConfigurationShader_h
#include "IConfiguration.h"
class CConfigurationShader : public IConfiguration
{
public:
CConfigurationShader(void) = default;
~CConfigurationShader(void) = default;
std::string getVSFilename(void) const;
#if defined(__EDITOR__)
void setVSFilename(std::string vs_filename);
#endif
std::string getFSFilename(void) const;
#if defined(__EDITOR__)
void setFSFilename(std::string fs_filename);
#endif
void serialize(pugi::xml_document& document, const std::string& path);
#if defined(__EDITOR__)
void deserialize(pugi::xml_node& node);
#endif
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
#endif
