// autogenerated: do not add any changes
#ifndef CConfigurationAccessor_h
#define CConfigurationAccessor_h
#include "CConfigurationLandscape.h"
#include "CConfigurationMaterial.h"
#include "CConfigurationModel.h"
#include "CConfigurationOcean.h"
#include "CConfigurationOutputTechnique.h"
#include "CConfigurationParticleEmitter.h"
#include "CConfigurationSSTechnique.h"
#include "CConfigurationTransition.h"
#include "CConfigurationWSTechnique.h"
class CConfigurationAccessor
{
public:
CConfigurationAccessor(void) = default;
~CConfigurationAccessor(void) = default;
void getConfigurationLandscape(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationMaterial(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationModel(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationOcean(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationOutputTechnique(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationParticleEmitter(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationSSTechnique(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationTransition(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getConfigurationWSTechnique(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
};
#endif
