// autogenerated: do not add any changes
#ifndef CConfigurationOutputTechnique_h
#define CConfigurationOutputTechnique_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationOutputTechnique : public IConfiguration
{
public:
CConfigurationOutputTechnique(void) = default;
~CConfigurationOutputTechnique(void) = default;
std::string getGUID(void) const;
#if defined(__EDITOR__)
void setGUID(std::string guid);
#endif
std::shared_ptr<CConfigurationMaterial> getConfigurationMaterial(void) const;
#if defined(__EDITOR__)
void setConfigurationMaterial(const std::shared_ptr<CConfigurationMaterial>& material);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
