// autogenerated: do not add any changes
#ifndef CConfigurationSkybox_h
#define CConfigurationSkybox_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationSkybox : public IConfigurationGameObject
{
public:
CConfigurationSkybox(void) = default;
~CConfigurationSkybox(void) = default;
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
void serialize(const std::string& filename);
};
#endif
