// autogenerated: do not add any changes
#ifndef CConfigurationAnimation_h
#define CConfigurationAnimation_h
#include "IConfiguration.h"
class CConfigurationAnimation : public IConfiguration
{
public:
CConfigurationAnimation(void) = default;
~CConfigurationAnimation(void) = default;
std::string getFilename(void) const;
std::string getName(void) const;
void serialize(pugi::xml_document& document, const std::string& path);
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
#endif
