// autogenerated: do not add any changes
#ifndef CConfigurationSkybox_h
#define CConfigurationSkybox_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationSkybox : public IConfigurationGameObject
{
public:
CConfigurationSkybox(void) = default;
~CConfigurationSkybox(void) = default;
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
#if defined(__EDITOR__)
void addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material);
#endif
#if defined(__EDITOR__)
void setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
