// autogenerated: do not add any changes
#ifndef CConfigurationShader_h
#define CConfigurationShader_h
#include "IConfiguration.h"
class CConfigurationShader : public IConfiguration
{
public:
CConfigurationShader(void) = default;
~CConfigurationShader(void) = default;
std::string getVSFilename(void) const;
std::string getFSFilename(void) const;
void serialize(pugi::xml_document& document, const std::string& path);
};
#endif
