// autogenerated: do not add any changes
#include "CConfigurationTexture.h"
std::string CConfigurationTexture::getFilename(void) const
{
const auto& iterator = m_attributes.find("/texture/filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
std::string CConfigurationTexture::getRenderOperationName(void) const
{
const auto& iterator = m_attributes.find("/texture/render_operation_name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
ui32 CConfigurationTexture::getSamplerIndex(void) const
{
const auto& iterator = m_attributes.find("/texture/sampler_index");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
GLenum CConfigurationTexture::getWrapMode(void) const
{
const auto& iterator = m_attributes.find("/texture/wrap_mode");
assert(iterator != m_attributes.end());
GLenum value; iterator->second->get(&value);
return value;
}
GLenum CConfigurationTexture::getMagFilter(void) const
{
const auto& iterator = m_attributes.find("/texture/mag_filter");
assert(iterator != m_attributes.end());
GLenum value; iterator->second->get(&value);
return value;
}
GLenum CConfigurationTexture::getMinFilter(void) const
{
const auto& iterator = m_attributes.find("/texture/min_filter");
assert(iterator != m_attributes.end());
GLenum value; iterator->second->get(&value);
return value;
}
void CConfigurationTexture::serialize(pugi::xml_document& document, const std::string& path)
{
pugi::xpath_node node;
node = document.select_single_node((path + "/texture").c_str());
std::string filename = node.node().attribute("filename").as_string();
IConfiguration::setAttribute("/texture/filename", std::make_shared<CConfigurationAttribute>(filename));
std::string render_operation_name = node.node().attribute("render_operation_name").as_string();
IConfiguration::setAttribute("/texture/render_operation_name", std::make_shared<CConfigurationAttribute>(render_operation_name));
ui32 sampler_index = node.node().attribute("sampler_index").as_uint();
IConfiguration::setAttribute("/texture/sampler_index", std::make_shared<CConfigurationAttribute>(sampler_index));
std::string wrap_mode = node.node().attribute("wrap_mode").as_string();
assert(g_stringToGLenum.find(wrap_mode) != g_stringToGLenum.end());
GLenum wrap_modeEnum = g_stringToGLenum.find(wrap_mode)->second;
IConfiguration::setAttribute("/texture/wrap_mode", std::make_shared<CConfigurationAttribute>(wrap_modeEnum));
std::string mag_filter = node.node().attribute("mag_filter").as_string();
assert(g_stringToGLenum.find(mag_filter) != g_stringToGLenum.end());
GLenum mag_filterEnum = g_stringToGLenum.find(mag_filter)->second;
IConfiguration::setAttribute("/texture/mag_filter", std::make_shared<CConfigurationAttribute>(mag_filterEnum));
std::string min_filter = node.node().attribute("min_filter").as_string();
assert(g_stringToGLenum.find(min_filter) != g_stringToGLenum.end());
GLenum min_filterEnum = g_stringToGLenum.find(min_filter)->second;
IConfiguration::setAttribute("/texture/min_filter", std::make_shared<CConfigurationAttribute>(min_filterEnum));
}
void CConfigurationTexture::serialize(pugi::xml_document& document, pugi::xpath_node& node)
{
std::string filename = node.node().attribute("filename").as_string();
IConfiguration::setAttribute("/texture/filename", std::make_shared<CConfigurationAttribute>(filename));
std::string render_operation_name = node.node().attribute("render_operation_name").as_string();
IConfiguration::setAttribute("/texture/render_operation_name", std::make_shared<CConfigurationAttribute>(render_operation_name));
ui32 sampler_index = node.node().attribute("sampler_index").as_uint();
IConfiguration::setAttribute("/texture/sampler_index", std::make_shared<CConfigurationAttribute>(sampler_index));
std::string wrap_mode = node.node().attribute("wrap_mode").as_string();
assert(g_stringToGLenum.find(wrap_mode) != g_stringToGLenum.end());
GLenum wrap_modeEnum = g_stringToGLenum.find(wrap_mode)->second;
IConfiguration::setAttribute("/texture/wrap_mode", std::make_shared<CConfigurationAttribute>(wrap_modeEnum));
std::string mag_filter = node.node().attribute("mag_filter").as_string();
assert(g_stringToGLenum.find(mag_filter) != g_stringToGLenum.end());
GLenum mag_filterEnum = g_stringToGLenum.find(mag_filter)->second;
IConfiguration::setAttribute("/texture/mag_filter", std::make_shared<CConfigurationAttribute>(mag_filterEnum));
std::string min_filter = node.node().attribute("min_filter").as_string();
assert(g_stringToGLenum.find(min_filter) != g_stringToGLenum.end());
GLenum min_filterEnum = g_stringToGLenum.find(min_filter)->second;
IConfiguration::setAttribute("/texture/min_filter", std::make_shared<CConfigurationAttribute>(min_filterEnum));
}
