// autogenerated: do not add any changes
#include "CConfigurationAnimation.h"
std::string CConfigurationAnimation::getFilename(void) const
{
const auto& iterator = m_attributes.find("/animation/filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void CConfigurationAnimation::set_filename(std::string filename)
{
IConfiguration::setAttribute("/animation/filename", std::make_shared<CConfigurationAttribute>(filename));
}
#endif
std::string CConfigurationAnimation::getName(void) const
{
const auto& iterator = m_attributes.find("/animation/name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void CConfigurationAnimation::set_name(std::string name)
{
IConfiguration::setAttribute("/animation/name", std::make_shared<CConfigurationAttribute>(name));
}
#endif
void CConfigurationAnimation::serialize(pugi::xml_document& document, const std::string& path)
{
pugi::xpath_node node;
node = document.select_single_node((path + "/animation").c_str());
std::string filename = node.node().attribute("filename").as_string();
IConfiguration::setAttribute("/animation/filename", std::make_shared<CConfigurationAttribute>(filename));
std::string name = node.node().attribute("name").as_string();
IConfiguration::setAttribute("/animation/name", std::make_shared<CConfigurationAttribute>(name));
}
void CConfigurationAnimation::serialize(pugi::xml_document& document, pugi::xpath_node& node)
{
std::string filename = node.node().attribute("filename").as_string();
IConfiguration::setAttribute("/animation/filename", std::make_shared<CConfigurationAttribute>(filename));
std::string name = node.node().attribute("name").as_string();
IConfiguration::setAttribute("/animation/name", std::make_shared<CConfigurationAttribute>(name));
}
