// autogenerated: do not add any changes
#ifndef CConfigurationOutputTechnique_h
#define CConfigurationOutputTechnique_h
#include "IConfiguration.h"
class CConfigurationOutputTechnique : public IConfiguration
{
public:
CConfigurationOutputTechnique(void) = default;
~CConfigurationOutputTechnique(void) = default;
std::string getGUID(void) const;
std::shared_ptr<CConfigurationMaterial> getConfigurationMaterial(void) const;
std::shared_ptr<CConfigurationOutputTechnique> serialize(const std::string& filename);
};
#endif
