// autogenerated: do not add any changes
#ifndef CConfigurationLandscape_h
#define CConfigurationLandscape_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationLandscape : public IConfigurationGameObject
{
public:
CConfigurationLandscape(void) = default;
~CConfigurationLandscape(void) = default;
std::string getHeightmapDataFilename(void) const;
std::string getSplattingDataFilename(void) const;
ui32 getSize(void) const;
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
void serialize(const std::string& filename);
};
#endif
