// autogenerated: do not add any changes
#ifndef CConfigurationParticleEmitter_h
#define CConfigurationParticleEmitter_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationParticleEmitter : public IConfigurationGameObject
{
public:
CConfigurationParticleEmitter(void) = default;
~CConfigurationParticleEmitter(void) = default;
i32 getZOrder(void) const;
#if defined(__EDITOR__)
void setZOrder(i32 z_order);
#endif
ui32 getNumParticles(void) const;
#if defined(__EDITOR__)
void setNumParticles(ui32 num_particles);
#endif
ui32 getDuration(void) const;
#if defined(__EDITOR__)
void setDuration(ui32 duration);
#endif
f32 getDurationRandomess(void) const;
#if defined(__EDITOR__)
void setDurationRandomess(f32 duration_randomness);
#endif
f32 getVelocitySensitivity(void) const;
#if defined(__EDITOR__)
void setVelocitySensitivity(f32 velocity_sensitivity);
#endif
f32 getMinHorizontalVelocity(void) const;
#if defined(__EDITOR__)
void setMinHorizontalVelocity(f32 min_horizontal_velocity);
#endif
f32 getMaxHorizontalVelocity(void) const;
#if defined(__EDITOR__)
void setMaxHorizontalVelocity(f32 max_horizontal_velocity);
#endif
f32 getMinVerticalVelocity(void) const;
#if defined(__EDITOR__)
void setMinVerticalVelocity(f32 min_vertical_velocity);
#endif
f32 getMaxVerticalVelocity(void) const;
#if defined(__EDITOR__)
void setMaxVerticalVelocity(f32 max_vertical_velocity);
#endif
f32 getEndVelocity(void) const;
#if defined(__EDITOR__)
void setEndVelocity(f32 end_velocity);
#endif
f32 getGravityX(void) const;
#if defined(__EDITOR__)
void setGravityX(f32 gravity_x);
#endif
f32 getGravityY(void) const;
#if defined(__EDITOR__)
void setGravityY(f32 gravity_y);
#endif
f32 getGravityZ(void) const;
#if defined(__EDITOR__)
void setGravityZ(f32 gravity_z);
#endif
ui8 getSourceColorR(void) const;
#if defined(__EDITOR__)
void setSourceColorR(ui8 source_color_r);
#endif
ui8 getSourceColorG(void) const;
#if defined(__EDITOR__)
void setSourceColorG(ui8 source_color_g);
#endif
ui8 getSourceColorB(void) const;
#if defined(__EDITOR__)
void setSourceColorB(ui8 source_color_b);
#endif
ui8 getSourceColorA(void) const;
#if defined(__EDITOR__)
void setSourceColorA(ui8 source_color_a);
#endif
ui8 getDestinationColorR(void) const;
#if defined(__EDITOR__)
void setDestinationColorR(ui8 destination_color_r);
#endif
ui8 getDestinationColorG(void) const;
#if defined(__EDITOR__)
void setDestinationColorG(ui8 destination_color_g);
#endif
ui8 getDestinationColorB(void) const;
#if defined(__EDITOR__)
void setDestinationColorB(ui8 destination_color_b);
#endif
ui8 getDestinationColorA(void) const;
#if defined(__EDITOR__)
void setDestinationColorA(ui8 destination_color_a);
#endif
f32 getSourceSizeX(void) const;
#if defined(__EDITOR__)
void setSourceSizeX(f32 source_size_x);
#endif
f32 getSourceSizeY(void) const;
#if defined(__EDITOR__)
void setSourceSizeY(f32 source_size_y);
#endif
f32 getDestinationSizeX(void) const;
#if defined(__EDITOR__)
void setDestinationSizeX(f32 destination_size_x);
#endif
f32 getDestinationSizeY(void) const;
#if defined(__EDITOR__)
void setDestinationSizeY(f32 destination_size_y);
#endif
ui32 getMinEmittInterval(void) const;
#if defined(__EDITOR__)
void setMinEmittInterval(ui32 min_emitt_interval);
#endif
ui32 getMaxEmittInterval(void) const;
#if defined(__EDITOR__)
void setMaxEmittInterval(ui32 max_emitt_interval);
#endif
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
#if defined(__EDITOR__)
void addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material);
#endif
#if defined(__EDITOR__)
void setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
