//
//  HEnums.h
//  indi2dEngine-Core
//
//  Created by Sergey Sergeev on 5/7/13.
//  Copyright (c) 2013 Sergey Sergeev. All rights reserved.
//

#ifndef HEnums_h
#define HEnums_h

enum E_RESOURCE_TYPE
{
    E_RESOURCE_TYPE_UNKNOWN = 0,
    E_RESOURCE_TYPE_TEXTURE,
    E_RESOURCE_TYPE_SHADER
};

enum E_SHADER_ATTRIBUTE
{
    E_SHADER_ATTRIBUTE_POSITION = 0,
    E_SHADER_ATTRIBUTE_TEXCOORD,
    E_SHADER_ATTRIBUTE_NORMAL,
    E_SHADER_ATTRIBUTE_TANGENT,
    E_SHADER_ATTRIBUTE_COLOR,
    E_SHADER_ATTRIBUTE_MAX
};

enum E_SHADER_UNIFORM
{
    E_SHADER_UNIFORM_MATRIX_WORLD = 0,
    E_SHADER_UNIFORM_MATRIX_VIEW,
    E_SHADER_UNIFORM_MATRIX_PROJECTION,
    E_SHADER_UNIFORM_VECTOR_CAMERA_POSITION,
    E_SHADER_UNIFORM_VECTOR_LIGHT_POSITION,
    E_SHADER_UNIFORM_VECTOR_CLIP_PLANE,
    E_SHADER_UNIFORM_MAX
};

enum E_SHADER_SAMPLER
{
    E_SHADER_SAMPLER_01 = 0,
    E_SHADER_SAMPLER_02,
    E_SHADER_SAMPLER_03,
    E_SHADER_SAMPLER_04,
    E_SHADER_SAMPLER_05,
    E_SHADER_SAMPLER_06,
    E_SHADER_SAMPLER_07,
    E_SHADER_SAMPLER_08,
    E_SHADER_SAMPLER_MAX
};

#endif
