// autogenerated: do not add any changes
#include "CConfigurationCustomModel.h"
i32 CConfigurationCustomModel::getZOrder(void) const
{
const auto& iterator = m_attributes.find("/custom_model/z_order");
assert(iterator != m_attributes.end());
i32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void CConfigurationCustomModel::setZOrder(i32 z_order)
{
IConfiguration::setAttribute("/custom_model/z_order", std::make_shared<CConfigurationAttribute>(z_order));
}
#endif
std::vector<std::shared_ptr<IConfiguration>> CConfigurationCustomModel::getMaterialsConfigurations(void) const
{
const auto& iterator = m_configurations.find("/custom_model/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<IConfiguration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void CConfigurationCustomModel::addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material)
{
IConfiguration::setConfiguration("/custom_model/materials/material", material);
}
#endif
#if defined(__EDITOR__)
void CConfigurationCustomModel::setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index)
{
IConfiguration::setConfiguration("/custom_model/materials/material", material, index);
}
#endif
void CConfigurationCustomModel::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = IConfiguration::openXMLDocument(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/custom_model");
i32 z_order = node.node().attribute("z_order").as_int();
IConfiguration::setAttribute("/custom_model/z_order", std::make_shared<CConfigurationAttribute>(z_order));
pugi::xpath_node_set material_nodes = document.select_nodes("/custom_model/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<CConfigurationMaterial> material = std::make_shared<CConfigurationMaterial>();
material->serialize((*iterator).node().attribute("filename").as_string());
IConfiguration::setConfiguration("/custom_model/materials/material", material);
}
}
#if defined(__EDITOR__)
void CConfigurationCustomModel::deserialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = document.load("");
assert(result.status == pugi::status_ok);
pugi::xml_node node = document.append_child("custom_model");
pugi::xml_node parent_node = node;
pugi::xml_attribute attribute;
attribute = node.append_attribute("z_order");
i32 z_order = CConfigurationCustomModel::getZOrder();
attribute.set_value(z_order);
node = parent_node.append_child("materials");
for(const auto& iterator : CConfigurationCustomModel::getMaterialsConfigurations())
{
std::shared_ptr<CConfigurationMaterial> configuration = std::static_pointer_cast<CConfigurationMaterial>(iterator);
pugi::xml_node child_node = node.append_child("material");
attribute = child_node.append_attribute("filename");
attribute.set_value(configuration->getFilename().c_str());
}
document.save_file(filename.c_str());
}
#endif
