// autogenerated: do not add any changes
#include "CConfigurationCustomModel.h"
std::vector<std::shared_ptr<IConfiguration>> CConfigurationCustomModel::getMaterialsConfigurations(void) const
{
const auto& iterator = m_configurations.find("/custom_model/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<IConfiguration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void CConfigurationCustomModel::addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material)
{
IConfiguration::setConfiguration("/custom_model/materials/material", material);
}
#endif
#if defined(__EDITOR__)
void CConfigurationCustomModel::setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index)
{
IConfiguration::setConfiguration("/custom_model/materials/material", material, index);
}
#endif
void CConfigurationCustomModel::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = IConfiguration::openXMLDocument(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/custom_model");
pugi::xpath_node_set material_nodes = document.select_nodes("/custom_model/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<CConfigurationMaterial> material = std::make_shared<CConfigurationMaterial>();
material->serialize((*iterator).node().attribute("filename").as_string());
IConfiguration::setConfiguration("/custom_model/materials/material", material);
}
}
