// autogenerated: do not add any changes
#include "CEConfigurationAccessor.h"
void CEConfigurationAccessor::getConfigurationCustomModel(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const
{
std::shared_ptr<CConfigurationCustomModel> configuration = std::make_shared<CConfigurationCustomModel>();
configuration->serialize(filename);
assert(configuration != nullptr);
assert(handler != nullptr);
handler->onConfigurationLoaded(configuration, true);
}
