// autogenerated: do not add any changes
#ifndef CConfigurationBrushElement_h
#define CConfigurationBrushElement_h
#include "IConfiguration.h"
#include "CConfigurationCustomModel.h"
class CConfigurationBrushElement : public IConfiguration
{
public:
CConfigurationBrushElement(void) = default;
~CConfigurationBrushElement(void) = default;
std::string getName(void) const;
ui8 getColorR(void) const;
ui8 getColorG(void) const;
ui8 getColorB(void) const;
ui8 getColorA(void) const;
f32 getWidth(void) const;
f32 getHeight(void) const;
std::shared_ptr<CConfigurationCustomModel> getCustomModelConfiguration(void) const;
void serialize(pugi::xml_document& document, const std::string& path);
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
#endif
