// autogenerated: do not add any changes
#ifndef CConfigurationLandscapeBrush_h
#define CConfigurationLandscapeBrush_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CConfigurationLandscapeBrush : public IConfiguration
{
public:
CConfigurationLandscapeBrush(void) = default;
~CConfigurationLandscapeBrush(void) = default;
f32 getSize(void) const;
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
void serialize(pugi::xml_document& document, const std::string& path);
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
#endif
