// autogenerated: do not add any changes
#include "CMEConfigurationAccessor.h"
void CMEConfigurationAccessor::getConfigurationLandscapeBrush(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const
{
std::shared_ptr<CConfigurationLandscapeBrush> configuration = std::make_shared<CConfigurationLandscapeBrush>();
configuration->serialize(filename);
assert(configuration != nullptr);
assert(handler != nullptr);
handler->onConfigurationLoaded(configuration, true);
}
