// autogenerated: do not add any changes
#ifndef CMEConfigurationSceneStage_h
#define CMEConfigurationSceneStage_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CMEConfigurationSceneStage : public IConfigurationGameObject
{
public:
CMEConfigurationSceneStage(void) = default;
~CMEConfigurationSceneStage(void) = default;
f32 getSizeX(void) const;
#if defined(__EDITOR__)
void setSizeX(f32 size_x);
#endif
f32 getSizeY(void) const;
#if defined(__EDITOR__)
void setSizeY(f32 size_y);
#endif
f32 getSizeZ(void) const;
#if defined(__EDITOR__)
void setSizeZ(f32 size_z);
#endif
i32 getZOrder(void) const;
#if defined(__EDITOR__)
void setZOrder(i32 z_order);
#endif
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
#if defined(__EDITOR__)
void addMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material);
#endif
#if defined(__EDITOR__)
void setMaterialsConfigurations(const std::shared_ptr<CConfigurationMaterial>& material, i32 index);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
#endif
