// autogenerated: do not add any changes, added changes will be lost.
#ifndef CMEConfigurationAccessor_h
#define CMEConfigurationAccessor_h
#include "CEConfigurationAccessor.h"
#include "CMEConfigurationLandscapeBrush.h"
#include "CMEConfigurationModelBrush.h"
class CMEConfigurationAccessor: public CEConfigurationAccessor
{
public:
CMEConfigurationAccessor(void) = default;
~CMEConfigurationAccessor(void) = default;
void getMEConfigurationLandscapeBrush(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
void getMEConfigurationModelBrush(const std::string& filename, const std::shared_ptr<IConfigurationLoadingHandler>& handler) const;
};
#endif
