// autogenerated: do not add any changes
#ifndef CMEConfigurationAccessor_h
#define CMEConfigurationAccessor_h
#include "CEConfigurationAccessor.h"
class CMEConfigurationAccessor: public CEConfigurationAccessor
{
public:
CMEConfigurationAccessor(void) = default;
~CMEConfigurationAccessor(void) = default;
};
#endif
