// autogenerated: do not add any changes
#ifndef CMEConfigurationLandscapeBrush_h
#define CMEConfigurationLandscapeBrush_h
#include "IConfiguration.h"
#include "CConfigurationMaterial.h"
class CMEConfigurationLandscapeBrush : public IConfigurationGameObject
{
public:
CMEConfigurationLandscapeBrush(void) = default;
~CMEConfigurationLandscapeBrush(void) = default;
f32 getSize(void) const;
std::vector<std::shared_ptr<IConfiguration>> getMaterialsConfigurations(void) const;
void serialize(const std::string& filename);
};
#endif
