#ifndef HMEConfigurationDeclarations_h
#define HMEConfigurationDeclarations_h
class CMEConfigurationBrushElement;
typedef std::shared_ptr<CMEConfigurationBrushElement> CSharedMEConfigurationBrushElement;
typedef const CSharedMEConfigurationBrushElement& CSharedMEConfigurationBrushElementRef;
class CMEConfigurationLandscapeBrush;
typedef std::shared_ptr<CMEConfigurationLandscapeBrush> CSharedMEConfigurationLandscapeBrush;
typedef const CSharedMEConfigurationLandscapeBrush& CSharedMEConfigurationLandscapeBrushRef;
class CMEConfigurationModelBrush;
typedef std::shared_ptr<CMEConfigurationModelBrush> CSharedMEConfigurationModelBrush;
typedef const CSharedMEConfigurationModelBrush& CSharedMEConfigurationModelBrushRef;
#endif
