#ifndef HMEConfigurationDeclarations_h
#define HMEConfigurationDeclarations_h
class CConfigurationBrushElement;
typedef std::shared_ptr<CConfigurationBrushElement> CSharedConfigurationBrushElement;
typedef const CSharedConfigurationBrushElement& CSharedConfigurationBrushElementRef;
class CConfigurationLandscapeBrush;
typedef std::shared_ptr<CConfigurationLandscapeBrush> CSharedConfigurationLandscapeBrush;
typedef const CSharedConfigurationLandscapeBrush& CSharedConfigurationLandscapeBrushRef;
#endif
