// autogenerated: do not add any changes
#ifndef CConfigurationModel_h
#define CConfigurationModel_h
class CConfigurationModel : public IConfiguration
{
public:
CConfigurationModel(void) = default
~CConfigurationModel(void) = default
std::string getFilename(void) const;
bool isBatching(void) const;
std::vector<std::shared_ptr<CConfigurationMaterial>> getMaterialsConfigurations(void) const;
std::vector<std::shared_ptr<CConfigurationAnimation>> getAnimationsConfigurations(void) const;
std::shared_ptr<CConfigurationModel> serialize(pugi::xml_document& document, const std::string& path);
};
