// autogenerated: do not add any changes
#ifndef CConfigurationSSTechnique_h
#define CConfigurationSSTechnique_h
class CConfigurationSSTechnique : public IConfiguration
{
public:
CConfigurationSSTechnique(void) = default
~CConfigurationSSTechnique(void) = default
std::string getGUID(void) const;
ui32 getScreenWidth(void) const;
ui32 getScreenHeight(void) const;
std::shared_ptr<CConfigurationMaterial> getConfigurationMaterial(void) const;
std::shared_ptr<CConfigurationSSTechnique> serialize(const std::string& filename);
