// autogenerated: do not add any changes
#ifndef CConfigurationTexture_h
#define CConfigurationTexture_h
class CConfigurationTexture : public IConfiguration
{
public:
CConfigurationTexture(void) = default
~CConfigurationTexture(void) = default
std::string getFilename(void) const;
std::string getRenderOperationName(void) const;
ui32 getSamplerIndex(void) const;
GLenum getWrapMode(void) const;
GLenum getMagFilter(void) const;
GLenum getMinFilter(void) const;
std::shared_ptr<CConfigurationTexture> serialize(pugi::xml_document& document, const std::string& path);
};
