// autogenerated: do not add any changes
#ifndef CConfigurationWSTechnique_h
#define CConfigurationWSTechnique_h
class CConfigurationWSTechnique : public IConfiguration
{
public:
CConfigurationWSTechnique(void) = default
~CConfigurationWSTechnique(void) = default
std::string getGUID(void) const;
bool areDrawBoundingBoxes(void) const;
ui32 getIndex(void) const;
ui32 getScreenWidth(void) const;
ui32 getScreenHeight(void) const;
f32 getClearColorR(void) const;
f32 getClearColorG(void) const;
f32 getClearColorB(void) const;
f32 getClearColorA(void) const;
std::shared_ptr<CConfigurationWSTechnique> serialize(const std::string& filename);
};
