/********************************************************************************
** Form generated from reading UI file 'CMainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.4.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CMAINWINDOW_H
#define UI_CMAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CMainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *m_mainMenuTabs;
    QWidget *m_sceneTab;
    QTabWidget *m_landscapePropertiesTab;
    QWidget *m_landscapeHeightmapTab;
    QGroupBox *generateGroupBox;
    QSpinBox *m_octavesSpinBox;
    QLabel *label;
    QDoubleSpinBox *m_frequencySpinBox;
    QLabel *label_2;
    QLabel *label_3;
    QSpinBox *m_seedSpinBox;
    QPushButton *generateButton;
    QLabel *label_4;
    QSpinBox *m_sizeXSpinBox;
    QLabel *label_5;
    QLabel *label_6;
    QSpinBox *m_sizeYSpinBox;
    QGroupBox *editGroupBox;
    QSlider *m_smoothSlider;
    QSlider *m_brushSizeSlider;
    QLabel *m_falloffLabel;
    QLabel *m_brushSizeLabel;
    QLabel *m_smoothLabel;
    QSlider *m_brushStrengthSlider;
    QLabel *m_brushStrengthLabel;
    QSlider *m_falloffSlider;
    QWidget *m_landscapeTexturesTab;
    QPushButton *m_texture01Btn;
    QLabel *m_texture01Label;
    QLabel *m_texture02Label;
    QPushButton *m_texture02Btn;
    QLabel *m_texture03Label;
    QPushButton *m_texture03Btn;
    QLabel *m_texture01Img;
    QLabel *m_texture02Img;
    QLabel *m_texture03Img;
    QSpinBox *m_textureTilling01SpinBox;
    QLabel *m_textureTilling01Label;
    QLabel *m_textureTilling02Label;
    QSpinBox *m_textureTilling02SpinBox;
    QLabel *m_textureTilling03Label;
    QSpinBox *m_textureTilling03SpinBox;
    QWidget *m_landscapeGameobjectsTab;
    QWidget *m_modelsOpenGLView;
    QListWidget *m_modelsList;
    QPushButton *m_addModelToSceneButton;
    QWidget *m_oglWindow;
    QLabel *m_heightmapGenerationStatisticLabel;
    QWidget *m_gameObjectTab;
    QWidget *m_gameObjectGLWindow;
    QTabWidget *m_goeSettingsTab;
    QWidget *m_goeMainSettingTab;
    QPushButton *m_createGameObjectConfiguration;
    QWidget *m_goeMaterialsSettingTab;
    QComboBox *m_materialsComboBox;
    QCheckBox *m_cullFaceCheckBox;
    QComboBox *m_cullModeComboBox;
    QCheckBox *m_depthTestCheckBox;
    QCheckBox *m_depthMaskCheckBox;
    QCheckBox *m_blendingCheckBox;
    QComboBox *m_blendingSourceComboBox;
    QComboBox *m_blendingDesinationComboBox;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QCheckBox *m_clippingCheckBox;
    QDoubleSpinBox *m_clippingXSpinBox;
    QDoubleSpinBox *m_clippingYSpinBox;
    QDoubleSpinBox *m_clippingZSpinBox;
    QDoubleSpinBox *m_clippingWSpinBox;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QCheckBox *m_reflectingCheckBox;
    QCheckBox *m_shadowingCheckBox;
    QCheckBox *m_debuggingCheckBox;
    QPushButton *m_shaderButton;
    QPushButton *m_texture1LoadButton;
    QLabel *m_texture01Label_2;
    QLabel *m_texture1Image;
    QLabel *m_texture01Label_3;
    QLabel *m_texture2Image;
    QPushButton *m_texture2LoadButton;
    QLabel *m_texture01Label_4;
    QLabel *m_texture3Image;
    QPushButton *m_texture3LoadButton;
    QCheckBox *m_materialEnabledCheckBox;
    QRadioButton *m_drawCurrentRadioButton;
    QRadioButton *m_drawAllRadioButton;
    QWidget *m_goeAnimationsSettingTab;
    QWidget *m_particlesTab;
    QWidget *m_particlesGLWindow;
    QTabWidget *m_poeSettingsTab;
    QWidget *m_poeMainSettingTab;
    QLabel *label_21;
    QDoubleSpinBox *m_numParticlesSpinBox;
    QLabel *label_22;
    QDoubleSpinBox *m_durationSpinBox;
    QLabel *label_23;
    QDoubleSpinBox *m_durationRanomnessSpinBox;
    QLabel *label_24;
    QDoubleSpinBox *m_velocitySensitivitySpinBox;
    QDoubleSpinBox *m_minHorizontalVelocitySpinBox;
    QLabel *label_25;
    QDoubleSpinBox *m_maxHorizontalVelocitySpinBox;
    QLabel *label_26;
    QDoubleSpinBox *m_minVerticalVelocitySpinBox;
    QLabel *label_27;
    QLabel *label_28;
    QDoubleSpinBox *m_maxVerticalVelocitySpinBox;
    QDoubleSpinBox *m_endVelocitySpinBox;
    QLabel *label_29;
    QDoubleSpinBox *m_gravityXSpinBox;
    QLabel *label_30;
    QLabel *label_31;
    QDoubleSpinBox *m_gravityYSpinBox;
    QDoubleSpinBox *m_gravityZSpinBox;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QDoubleSpinBox *m_sourceColorRSpinBox;
    QDoubleSpinBox *m_sourceColorGSpinBox;
    QDoubleSpinBox *m_sourceColorBSpinBox;
    QDoubleSpinBox *m_sourceColorASpinBox;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QDoubleSpinBox *m_destinationColorASpinBox;
    QLabel *label_41;
    QDoubleSpinBox *m_destinationColorBSpinBox;
    QLabel *label_42;
    QDoubleSpinBox *m_destinationColorGSpinBox;
    QDoubleSpinBox *m_destinationColorRSpinBox;
    QLabel *label_43;
    QLabel *label_44;
    QDoubleSpinBox *m_sourceSizeYSpinBox;
    QLabel *label_45;
    QLabel *label_46;
    QDoubleSpinBox *m_sourceSizeXSpinBox;
    QDoubleSpinBox *m_destinationSizeXSpinBox;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QDoubleSpinBox *m_destinationSizeYSpinBox;
    QDoubleSpinBox *m_minEmittIntervalSpinBox;
    QLabel *label_50;
    QLabel *label_51;
    QDoubleSpinBox *m_maxEmittIntervalSpinBox;
    QWidget *m_poeMaterialsSettingTab;
    QComboBox *m_materialsComboBox_2;
    QCheckBox *m_cullFaceCheckBox_2;
    QComboBox *m_cullModeComboBox_2;
    QCheckBox *m_depthTestCheckBox_2;
    QCheckBox *m_depthMaskCheckBox_2;
    QCheckBox *m_blendingCheckBox_2;
    QComboBox *m_blendingSourceComboBox_2;
    QComboBox *m_blendingDesinationComboBox_2;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QCheckBox *m_clippingCheckBox_2;
    QDoubleSpinBox *m_clippingXSpinBox_2;
    QDoubleSpinBox *m_clippingYSpinBox_2;
    QDoubleSpinBox *m_clippingZSpinBox_2;
    QDoubleSpinBox *m_clippingWSpinBox_2;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QCheckBox *m_reflectingCheckBox_2;
    QCheckBox *m_shadowingCheckBox_2;
    QCheckBox *m_debuggingCheckBox_2;
    QPushButton *m_shaderButton_2;
    QPushButton *m_texture1LoadButton_2;
    QLabel *m_texture01Label_5;
    QLabel *m_texture1Image_2;
    QLabel *m_texture01Label_6;
    QLabel *m_texture2Image_2;
    QPushButton *m_texture2LoadButton_2;
    QLabel *m_texture01Label_7;
    QLabel *m_texture3Image_2;
    QPushButton *m_texture3LoadButton_2;
    QCheckBox *m_materialEnabledCheckBox_2;
    QRadioButton *m_drawCurrentRadioButton_2;
    QRadioButton *m_drawAllRadioButton_2;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *CMainWindow)
    {
        if (CMainWindow->objectName().isEmpty())
            CMainWindow->setObjectName(QStringLiteral("CMainWindow"));
        CMainWindow->setEnabled(true);
        CMainWindow->resize(1280, 800);
        CMainWindow->setMinimumSize(QSize(1280, 800));
        CMainWindow->setMaximumSize(QSize(1280, 800));
        CMainWindow->setStyleSheet(QStringLiteral("background-color: rgb(128, 128, 128);"));
        centralWidget = new QWidget(CMainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setEnabled(true);
        centralWidget->setStyleSheet(QStringLiteral("background-color: rgb(64, 64, 64);"));
        m_mainMenuTabs = new QTabWidget(centralWidget);
        m_mainMenuTabs->setObjectName(QStringLiteral("m_mainMenuTabs"));
        m_mainMenuTabs->setEnabled(true);
        m_mainMenuTabs->setGeometry(QRect(-1, -1, 1281, 781));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(64, 64, 64, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        m_mainMenuTabs->setPalette(palette);
        QFont font;
        font.setFamily(QStringLiteral("Menlo"));
        font.setPointSize(13);
        font.setBold(false);
        font.setWeight(50);
        m_mainMenuTabs->setFont(font);
        m_mainMenuTabs->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_mainMenuTabs->setDocumentMode(true);
        m_mainMenuTabs->setMovable(true);
        m_sceneTab = new QWidget();
        m_sceneTab->setObjectName(QStringLiteral("m_sceneTab"));
        m_landscapePropertiesTab = new QTabWidget(m_sceneTab);
        m_landscapePropertiesTab->setObjectName(QStringLiteral("m_landscapePropertiesTab"));
        m_landscapePropertiesTab->setEnabled(true);
        m_landscapePropertiesTab->setGeometry(QRect(930, -4, 350, 760));
        m_landscapePropertiesTab->setFont(font);
        m_landscapePropertiesTab->setStyleSheet(QStringLiteral("background-color: rgb(64, 64, 64);"));
        m_landscapePropertiesTab->setTabPosition(QTabWidget::West);
        m_landscapePropertiesTab->setTabShape(QTabWidget::Rounded);
        m_landscapePropertiesTab->setDocumentMode(true);
        m_landscapePropertiesTab->setMovable(true);
        m_landscapeHeightmapTab = new QWidget();
        m_landscapeHeightmapTab->setObjectName(QStringLiteral("m_landscapeHeightmapTab"));
        generateGroupBox = new QGroupBox(m_landscapeHeightmapTab);
        generateGroupBox->setObjectName(QStringLiteral("generateGroupBox"));
        generateGroupBox->setEnabled(true);
        generateGroupBox->setGeometry(QRect(10, 270, 301, 321));
        QFont font1;
        font1.setFamily(QStringLiteral("Menlo"));
        font1.setBold(true);
        font1.setWeight(75);
        generateGroupBox->setFont(font1);
        generateGroupBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_octavesSpinBox = new QSpinBox(generateGroupBox);
        m_octavesSpinBox->setObjectName(QStringLiteral("m_octavesSpinBox"));
        m_octavesSpinBox->setEnabled(true);
        m_octavesSpinBox->setGeometry(QRect(160, 100, 81, 24));
        m_octavesSpinBox->setMinimum(1);
        m_octavesSpinBox->setMaximum(16);
        label = new QLabel(generateGroupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setEnabled(true);
        label->setGeometry(QRect(10, 30, 191, 16));
        label->setFont(font1);
        m_frequencySpinBox = new QDoubleSpinBox(generateGroupBox);
        m_frequencySpinBox->setObjectName(QStringLiteral("m_frequencySpinBox"));
        m_frequencySpinBox->setEnabled(true);
        m_frequencySpinBox->setGeometry(QRect(160, 50, 81, 24));
        m_frequencySpinBox->setDecimals(1);
        m_frequencySpinBox->setMinimum(0.1);
        m_frequencySpinBox->setMaximum(64);
        m_frequencySpinBox->setSingleStep(0.1);
        label_2 = new QLabel(generateGroupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setEnabled(true);
        label_2->setGeometry(QRect(10, 80, 191, 16));
        label_2->setFont(font1);
        label_3 = new QLabel(generateGroupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setEnabled(true);
        label_3->setGeometry(QRect(10, 130, 191, 16));
        label_3->setFont(font1);
        m_seedSpinBox = new QSpinBox(generateGroupBox);
        m_seedSpinBox->setObjectName(QStringLiteral("m_seedSpinBox"));
        m_seedSpinBox->setEnabled(true);
        m_seedSpinBox->setGeometry(QRect(160, 150, 81, 24));
        m_seedSpinBox->setMaximum(65535);
        m_seedSpinBox->setValue(65535);
        generateButton = new QPushButton(generateGroupBox);
        generateButton->setObjectName(QStringLiteral("generateButton"));
        generateButton->setEnabled(true);
        generateButton->setGeometry(QRect(23, 280, 201, 32));
        generateButton->setFont(font1);
        label_4 = new QLabel(generateGroupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setEnabled(true);
        label_4->setGeometry(QRect(10, 190, 191, 16));
        label_4->setFont(font1);
        m_sizeXSpinBox = new QSpinBox(generateGroupBox);
        m_sizeXSpinBox->setObjectName(QStringLiteral("m_sizeXSpinBox"));
        m_sizeXSpinBox->setEnabled(true);
        m_sizeXSpinBox->setGeometry(QRect(160, 220, 81, 24));
        m_sizeXSpinBox->setMinimum(64);
        m_sizeXSpinBox->setMaximum(512);
        m_sizeXSpinBox->setSingleStep(64);
        m_sizeXSpinBox->setValue(512);
        label_5 = new QLabel(generateGroupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setEnabled(true);
        label_5->setGeometry(QRect(120, 220, 31, 16));
        label_5->setFont(font1);
        label_6 = new QLabel(generateGroupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setEnabled(true);
        label_6->setGeometry(QRect(120, 250, 31, 16));
        label_6->setFont(font1);
        m_sizeYSpinBox = new QSpinBox(generateGroupBox);
        m_sizeYSpinBox->setObjectName(QStringLiteral("m_sizeYSpinBox"));
        m_sizeYSpinBox->setEnabled(true);
        m_sizeYSpinBox->setGeometry(QRect(160, 250, 81, 24));
        m_sizeYSpinBox->setMinimum(64);
        m_sizeYSpinBox->setMaximum(512);
        m_sizeYSpinBox->setSingleStep(64);
        m_sizeYSpinBox->setValue(512);
        editGroupBox = new QGroupBox(m_landscapeHeightmapTab);
        editGroupBox->setObjectName(QStringLiteral("editGroupBox"));
        editGroupBox->setEnabled(true);
        editGroupBox->setGeometry(QRect(10, 10, 301, 251));
        QFont font2;
        font2.setFamily(QStringLiteral("Menlo"));
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setWeight(75);
        editGroupBox->setFont(font2);
        editGroupBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_smoothSlider = new QSlider(editGroupBox);
        m_smoothSlider->setObjectName(QStringLiteral("m_smoothSlider"));
        m_smoothSlider->setEnabled(true);
        m_smoothSlider->setGeometry(QRect(40, 200, 225, 22));
        m_smoothSlider->setMaximum(3);
        m_smoothSlider->setOrientation(Qt::Horizontal);
        m_smoothSlider->setInvertedAppearance(false);
        m_smoothSlider->setInvertedControls(false);
        m_smoothSlider->setTickPosition(QSlider::TicksAbove);
        m_smoothSlider->setTickInterval(1);
        m_brushSizeSlider = new QSlider(editGroupBox);
        m_brushSizeSlider->setObjectName(QStringLiteral("m_brushSizeSlider"));
        m_brushSizeSlider->setEnabled(true);
        m_brushSizeSlider->setGeometry(QRect(40, 50, 225, 22));
        m_brushSizeSlider->setMinimum(4);
        m_brushSizeSlider->setMaximum(32);
        m_brushSizeSlider->setSingleStep(2);
        m_brushSizeSlider->setOrientation(Qt::Horizontal);
        m_brushSizeSlider->setTickPosition(QSlider::TicksAbove);
        m_brushSizeSlider->setTickInterval(2);
        m_falloffLabel = new QLabel(editGroupBox);
        m_falloffLabel->setObjectName(QStringLiteral("m_falloffLabel"));
        m_falloffLabel->setEnabled(true);
        m_falloffLabel->setGeometry(QRect(40, 130, 225, 20));
        m_falloffLabel->setFont(font2);
        m_brushSizeLabel = new QLabel(editGroupBox);
        m_brushSizeLabel->setObjectName(QStringLiteral("m_brushSizeLabel"));
        m_brushSizeLabel->setEnabled(true);
        m_brushSizeLabel->setGeometry(QRect(40, 30, 225, 20));
        m_brushSizeLabel->setFont(font2);
        m_smoothLabel = new QLabel(editGroupBox);
        m_smoothLabel->setObjectName(QStringLiteral("m_smoothLabel"));
        m_smoothLabel->setEnabled(true);
        m_smoothLabel->setGeometry(QRect(40, 180, 225, 20));
        m_smoothLabel->setFont(font2);
        m_brushStrengthSlider = new QSlider(editGroupBox);
        m_brushStrengthSlider->setObjectName(QStringLiteral("m_brushStrengthSlider"));
        m_brushStrengthSlider->setEnabled(true);
        m_brushStrengthSlider->setGeometry(QRect(40, 100, 225, 22));
        m_brushStrengthSlider->setMinimum(1);
        m_brushStrengthSlider->setMaximum(10);
        m_brushStrengthSlider->setOrientation(Qt::Horizontal);
        m_brushStrengthSlider->setTickPosition(QSlider::TicksAbove);
        m_brushStrengthSlider->setTickInterval(1);
        m_brushStrengthLabel = new QLabel(editGroupBox);
        m_brushStrengthLabel->setObjectName(QStringLiteral("m_brushStrengthLabel"));
        m_brushStrengthLabel->setEnabled(true);
        m_brushStrengthLabel->setGeometry(QRect(40, 80, 225, 20));
        m_brushStrengthLabel->setFont(font2);
        m_falloffSlider = new QSlider(editGroupBox);
        m_falloffSlider->setObjectName(QStringLiteral("m_falloffSlider"));
        m_falloffSlider->setEnabled(true);
        m_falloffSlider->setGeometry(QRect(40, 150, 225, 22));
        m_falloffSlider->setOrientation(Qt::Horizontal);
        m_falloffSlider->setTickPosition(QSlider::TicksAbove);
        m_falloffSlider->setTickInterval(10);
        m_landscapePropertiesTab->addTab(m_landscapeHeightmapTab, QString());
        m_landscapeTexturesTab = new QWidget();
        m_landscapeTexturesTab->setObjectName(QStringLiteral("m_landscapeTexturesTab"));
        m_texture01Btn = new QPushButton(m_landscapeTexturesTab);
        m_texture01Btn->setObjectName(QStringLiteral("m_texture01Btn"));
        m_texture01Btn->setGeometry(QRect(142, 40, 91, 32));
        m_texture01Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label = new QLabel(m_landscapeTexturesTab);
        m_texture01Label->setObjectName(QStringLiteral("m_texture01Label"));
        m_texture01Label->setGeometry(QRect(10, 10, 221, 16));
        m_texture01Label->setFont(font1);
        m_texture01Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Label = new QLabel(m_landscapeTexturesTab);
        m_texture02Label->setObjectName(QStringLiteral("m_texture02Label"));
        m_texture02Label->setGeometry(QRect(10, 180, 221, 16));
        m_texture02Label->setFont(font1);
        m_texture02Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Btn = new QPushButton(m_landscapeTexturesTab);
        m_texture02Btn->setObjectName(QStringLiteral("m_texture02Btn"));
        m_texture02Btn->setGeometry(QRect(142, 210, 91, 32));
        m_texture02Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Label = new QLabel(m_landscapeTexturesTab);
        m_texture03Label->setObjectName(QStringLiteral("m_texture03Label"));
        m_texture03Label->setGeometry(QRect(10, 350, 221, 16));
        m_texture03Label->setFont(font1);
        m_texture03Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Btn = new QPushButton(m_landscapeTexturesTab);
        m_texture03Btn->setObjectName(QStringLiteral("m_texture03Btn"));
        m_texture03Btn->setGeometry(QRect(142, 380, 91, 32));
        m_texture03Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Img = new QLabel(m_landscapeTexturesTab);
        m_texture01Img->setObjectName(QStringLiteral("m_texture01Img"));
        m_texture01Img->setGeometry(QRect(10, 40, 128, 128));
        m_texture01Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Img = new QLabel(m_landscapeTexturesTab);
        m_texture02Img->setObjectName(QStringLiteral("m_texture02Img"));
        m_texture02Img->setGeometry(QRect(10, 210, 128, 128));
        m_texture02Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Img = new QLabel(m_landscapeTexturesTab);
        m_texture03Img->setObjectName(QStringLiteral("m_texture03Img"));
        m_texture03Img->setGeometry(QRect(10, 380, 128, 128));
        m_texture03Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling01SpinBox = new QSpinBox(m_landscapeTexturesTab);
        m_textureTilling01SpinBox->setObjectName(QStringLiteral("m_textureTilling01SpinBox"));
        m_textureTilling01SpinBox->setGeometry(QRect(150, 100, 91, 24));
        m_textureTilling01SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling01SpinBox->setMinimum(1);
        m_textureTilling01SpinBox->setMaximum(128);
        m_textureTilling01Label = new QLabel(m_landscapeTexturesTab);
        m_textureTilling01Label->setObjectName(QStringLiteral("m_textureTilling01Label"));
        m_textureTilling01Label->setGeometry(QRect(150, 80, 91, 20));
        m_textureTilling01Label->setFont(font1);
        m_textureTilling01Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02Label = new QLabel(m_landscapeTexturesTab);
        m_textureTilling02Label->setObjectName(QStringLiteral("m_textureTilling02Label"));
        m_textureTilling02Label->setGeometry(QRect(150, 250, 91, 20));
        m_textureTilling02Label->setFont(font1);
        m_textureTilling02Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02SpinBox = new QSpinBox(m_landscapeTexturesTab);
        m_textureTilling02SpinBox->setObjectName(QStringLiteral("m_textureTilling02SpinBox"));
        m_textureTilling02SpinBox->setGeometry(QRect(150, 270, 91, 24));
        m_textureTilling02SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02SpinBox->setMinimum(1);
        m_textureTilling02SpinBox->setMaximum(128);
        m_textureTilling03Label = new QLabel(m_landscapeTexturesTab);
        m_textureTilling03Label->setObjectName(QStringLiteral("m_textureTilling03Label"));
        m_textureTilling03Label->setGeometry(QRect(150, 420, 91, 20));
        m_textureTilling03Label->setFont(font1);
        m_textureTilling03Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling03SpinBox = new QSpinBox(m_landscapeTexturesTab);
        m_textureTilling03SpinBox->setObjectName(QStringLiteral("m_textureTilling03SpinBox"));
        m_textureTilling03SpinBox->setGeometry(QRect(150, 440, 91, 24));
        m_textureTilling03SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling03SpinBox->setMinimum(1);
        m_textureTilling03SpinBox->setMaximum(128);
        m_landscapePropertiesTab->addTab(m_landscapeTexturesTab, QString());
        m_landscapeGameobjectsTab = new QWidget();
        m_landscapeGameobjectsTab->setObjectName(QStringLiteral("m_landscapeGameobjectsTab"));
        m_modelsOpenGLView = new QWidget(m_landscapeGameobjectsTab);
        m_modelsOpenGLView->setObjectName(QStringLiteral("m_modelsOpenGLView"));
        m_modelsOpenGLView->setGeometry(QRect(13, 10, 300, 300));
        m_modelsOpenGLView->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_modelsList = new QListWidget(m_landscapeGameobjectsTab);
        m_modelsList->setObjectName(QStringLiteral("m_modelsList"));
        m_modelsList->setGeometry(QRect(10, 320, 301, 151));
        m_addModelToSceneButton = new QPushButton(m_landscapeGameobjectsTab);
        m_addModelToSceneButton->setObjectName(QStringLiteral("m_addModelToSceneButton"));
        m_addModelToSceneButton->setGeometry(QRect(10, 480, 301, 32));
        m_landscapePropertiesTab->addTab(m_landscapeGameobjectsTab, QString());
        m_oglWindow = new QWidget(m_sceneTab);
        m_oglWindow->setObjectName(QStringLiteral("m_oglWindow"));
        m_oglWindow->setEnabled(true);
        m_oglWindow->setGeometry(QRect(0, 0, 930, 761));
        m_oglWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_heightmapGenerationStatisticLabel = new QLabel(m_sceneTab);
        m_heightmapGenerationStatisticLabel->setObjectName(QStringLiteral("m_heightmapGenerationStatisticLabel"));
        m_heightmapGenerationStatisticLabel->setGeometry(QRect(130, 350, 671, 71));
        QFont font3;
        font3.setFamily(QStringLiteral("Menlo"));
        font3.setPointSize(18);
        m_heightmapGenerationStatisticLabel->setFont(font3);
        m_heightmapGenerationStatisticLabel->setAlignment(Qt::AlignCenter);
        m_mainMenuTabs->addTab(m_sceneTab, QString());
        m_gameObjectTab = new QWidget();
        m_gameObjectTab->setObjectName(QStringLiteral("m_gameObjectTab"));
        m_gameObjectGLWindow = new QWidget(m_gameObjectTab);
        m_gameObjectGLWindow->setObjectName(QStringLiteral("m_gameObjectGLWindow"));
        m_gameObjectGLWindow->setEnabled(true);
        m_gameObjectGLWindow->setGeometry(QRect(0, 0, 930, 756));
        m_gameObjectGLWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_goeSettingsTab = new QTabWidget(m_gameObjectTab);
        m_goeSettingsTab->setObjectName(QStringLiteral("m_goeSettingsTab"));
        m_goeSettingsTab->setEnabled(true);
        m_goeSettingsTab->setGeometry(QRect(930, -4, 351, 760));
        QFont font4;
        font4.setFamily(QStringLiteral("Menlo"));
        m_goeSettingsTab->setFont(font4);
        m_goeSettingsTab->setTabPosition(QTabWidget::West);
        m_goeSettingsTab->setDocumentMode(true);
        m_goeSettingsTab->setMovable(true);
        m_goeMainSettingTab = new QWidget();
        m_goeMainSettingTab->setObjectName(QStringLiteral("m_goeMainSettingTab"));
        m_createGameObjectConfiguration = new QPushButton(m_goeMainSettingTab);
        m_createGameObjectConfiguration->setObjectName(QStringLiteral("m_createGameObjectConfiguration"));
        m_createGameObjectConfiguration->setEnabled(true);
        m_createGameObjectConfiguration->setGeometry(QRect(20, 20, 281, 32));
        m_goeSettingsTab->addTab(m_goeMainSettingTab, QString());
        m_goeMaterialsSettingTab = new QWidget();
        m_goeMaterialsSettingTab->setObjectName(QStringLiteral("m_goeMaterialsSettingTab"));
        m_goeMaterialsSettingTab->setEnabled(true);
        m_goeMaterialsSettingTab->setFont(font4);
        m_materialsComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_materialsComboBox->setObjectName(QStringLiteral("m_materialsComboBox"));
        m_materialsComboBox->setGeometry(QRect(20, 60, 280, 26));
        m_cullFaceCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_cullFaceCheckBox->setObjectName(QStringLiteral("m_cullFaceCheckBox"));
        m_cullFaceCheckBox->setGeometry(QRect(20, 120, 271, 20));
        m_cullModeComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_cullModeComboBox->setObjectName(QStringLiteral("m_cullModeComboBox"));
        m_cullModeComboBox->setGeometry(QRect(118, 146, 182, 26));
        m_depthTestCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_depthTestCheckBox->setObjectName(QStringLiteral("m_depthTestCheckBox"));
        m_depthTestCheckBox->setGeometry(QRect(20, 180, 271, 20));
        m_depthMaskCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_depthMaskCheckBox->setObjectName(QStringLiteral("m_depthMaskCheckBox"));
        m_depthMaskCheckBox->setGeometry(QRect(20, 200, 271, 20));
        m_blendingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_blendingCheckBox->setObjectName(QStringLiteral("m_blendingCheckBox"));
        m_blendingCheckBox->setGeometry(QRect(20, 220, 271, 20));
        m_blendingSourceComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_blendingSourceComboBox->setObjectName(QStringLiteral("m_blendingSourceComboBox"));
        m_blendingSourceComboBox->setGeometry(QRect(118, 246, 182, 26));
        m_blendingDesinationComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_blendingDesinationComboBox->setObjectName(QStringLiteral("m_blendingDesinationComboBox"));
        m_blendingDesinationComboBox->setGeometry(QRect(118, 276, 182, 26));
        label_7 = new QLabel(m_goeMaterialsSettingTab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(22, 150, 62, 16));
        label_8 = new QLabel(m_goeMaterialsSettingTab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(22, 250, 62, 16));
        label_9 = new QLabel(m_goeMaterialsSettingTab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 280, 91, 16));
        m_clippingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_clippingCheckBox->setObjectName(QStringLiteral("m_clippingCheckBox"));
        m_clippingCheckBox->setGeometry(QRect(20, 310, 271, 20));
        m_clippingXSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingXSpinBox->setObjectName(QStringLiteral("m_clippingXSpinBox"));
        m_clippingXSpinBox->setGeometry(QRect(40, 337, 70, 24));
        m_clippingXSpinBox->setMinimum(-1);
        m_clippingXSpinBox->setMaximum(1);
        m_clippingXSpinBox->setSingleStep(0.1);
        m_clippingYSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingYSpinBox->setObjectName(QStringLiteral("m_clippingYSpinBox"));
        m_clippingYSpinBox->setGeometry(QRect(136, 337, 70, 24));
        m_clippingYSpinBox->setMinimum(-1);
        m_clippingYSpinBox->setMaximum(1);
        m_clippingYSpinBox->setSingleStep(0.1);
        m_clippingZSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingZSpinBox->setObjectName(QStringLiteral("m_clippingZSpinBox"));
        m_clippingZSpinBox->setGeometry(QRect(230, 337, 70, 24));
        m_clippingZSpinBox->setMinimum(-1);
        m_clippingZSpinBox->setMaximum(1);
        m_clippingZSpinBox->setSingleStep(0.1);
        m_clippingWSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingWSpinBox->setObjectName(QStringLiteral("m_clippingWSpinBox"));
        m_clippingWSpinBox->setGeometry(QRect(136, 367, 70, 24));
        m_clippingWSpinBox->setMinimum(-1024);
        m_clippingWSpinBox->setMaximum(1024);
        m_clippingWSpinBox->setSingleStep(0.1);
        label_10 = new QLabel(m_goeMaterialsSettingTab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(22, 340, 18, 16));
        label_11 = new QLabel(m_goeMaterialsSettingTab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(120, 340, 18, 16));
        label_12 = new QLabel(m_goeMaterialsSettingTab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(214, 340, 18, 16));
        label_13 = new QLabel(m_goeMaterialsSettingTab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(120, 370, 18, 16));
        m_reflectingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_reflectingCheckBox->setObjectName(QStringLiteral("m_reflectingCheckBox"));
        m_reflectingCheckBox->setGeometry(QRect(20, 400, 271, 20));
        m_shadowingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_shadowingCheckBox->setObjectName(QStringLiteral("m_shadowingCheckBox"));
        m_shadowingCheckBox->setGeometry(QRect(20, 420, 271, 20));
        m_debuggingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_debuggingCheckBox->setObjectName(QStringLiteral("m_debuggingCheckBox"));
        m_debuggingCheckBox->setGeometry(QRect(20, 440, 271, 20));
        m_shaderButton = new QPushButton(m_goeMaterialsSettingTab);
        m_shaderButton->setObjectName(QStringLiteral("m_shaderButton"));
        m_shaderButton->setGeometry(QRect(13, 470, 291, 24));
        m_texture1LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture1LoadButton->setObjectName(QStringLiteral("m_texture1LoadButton"));
        m_texture1LoadButton->setGeometry(QRect(20, 600, 64, 24));
        m_texture1LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_2 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_2->setObjectName(QStringLiteral("m_texture01Label_2"));
        m_texture01Label_2->setGeometry(QRect(10, 510, 81, 16));
        m_texture01Label_2->setFont(font1);
        m_texture01Label_2->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture1Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture1Image->setObjectName(QStringLiteral("m_texture1Image"));
        m_texture1Image->setGeometry(QRect(20, 530, 64, 64));
        m_texture1Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture1Image->setFrameShape(QFrame::Box);
        m_texture1Image->setScaledContents(true);
        m_texture1Image->setAlignment(Qt::AlignCenter);
        m_texture01Label_3 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_3->setObjectName(QStringLiteral("m_texture01Label_3"));
        m_texture01Label_3->setGeometry(QRect(100, 510, 81, 16));
        m_texture01Label_3->setFont(font1);
        m_texture01Label_3->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture2Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture2Image->setObjectName(QStringLiteral("m_texture2Image"));
        m_texture2Image->setGeometry(QRect(110, 530, 64, 64));
        m_texture2Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture2Image->setFrameShape(QFrame::Box);
        m_texture2Image->setScaledContents(true);
        m_texture2Image->setAlignment(Qt::AlignCenter);
        m_texture2LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture2LoadButton->setObjectName(QStringLiteral("m_texture2LoadButton"));
        m_texture2LoadButton->setGeometry(QRect(110, 600, 64, 24));
        m_texture2LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_4 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_4->setObjectName(QStringLiteral("m_texture01Label_4"));
        m_texture01Label_4->setGeometry(QRect(190, 510, 81, 16));
        m_texture01Label_4->setFont(font1);
        m_texture01Label_4->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture3Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture3Image->setObjectName(QStringLiteral("m_texture3Image"));
        m_texture3Image->setGeometry(QRect(200, 530, 64, 64));
        m_texture3Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture3Image->setFrameShape(QFrame::Box);
        m_texture3Image->setScaledContents(true);
        m_texture3Image->setAlignment(Qt::AlignCenter);
        m_texture3LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture3LoadButton->setObjectName(QStringLiteral("m_texture3LoadButton"));
        m_texture3LoadButton->setGeometry(QRect(200, 600, 64, 24));
        m_texture3LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_materialEnabledCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_materialEnabledCheckBox->setObjectName(QStringLiteral("m_materialEnabledCheckBox"));
        m_materialEnabledCheckBox->setGeometry(QRect(20, 90, 271, 20));
        m_drawCurrentRadioButton = new QRadioButton(m_goeMaterialsSettingTab);
        m_drawCurrentRadioButton->setObjectName(QStringLiteral("m_drawCurrentRadioButton"));
        m_drawCurrentRadioButton->setGeometry(QRect(22, 30, 141, 20));
        m_drawAllRadioButton = new QRadioButton(m_goeMaterialsSettingTab);
        m_drawAllRadioButton->setObjectName(QStringLiteral("m_drawAllRadioButton"));
        m_drawAllRadioButton->setGeometry(QRect(170, 30, 131, 20));
        m_goeSettingsTab->addTab(m_goeMaterialsSettingTab, QString());
        m_goeAnimationsSettingTab = new QWidget();
        m_goeAnimationsSettingTab->setObjectName(QStringLiteral("m_goeAnimationsSettingTab"));
        m_goeAnimationsSettingTab->setEnabled(true);
        m_goeSettingsTab->addTab(m_goeAnimationsSettingTab, QString());
        m_mainMenuTabs->addTab(m_gameObjectTab, QString());
        m_particlesTab = new QWidget();
        m_particlesTab->setObjectName(QStringLiteral("m_particlesTab"));
        m_particlesGLWindow = new QWidget(m_particlesTab);
        m_particlesGLWindow->setObjectName(QStringLiteral("m_particlesGLWindow"));
        m_particlesGLWindow->setEnabled(true);
        m_particlesGLWindow->setGeometry(QRect(0, 0, 930, 756));
        m_particlesGLWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_poeSettingsTab = new QTabWidget(m_particlesTab);
        m_poeSettingsTab->setObjectName(QStringLiteral("m_poeSettingsTab"));
        m_poeSettingsTab->setEnabled(true);
        m_poeSettingsTab->setGeometry(QRect(930, -4, 351, 760));
        m_poeSettingsTab->setFont(font4);
        m_poeSettingsTab->setTabPosition(QTabWidget::West);
        m_poeSettingsTab->setDocumentMode(true);
        m_poeSettingsTab->setMovable(true);
        m_poeMainSettingTab = new QWidget();
        m_poeMainSettingTab->setObjectName(QStringLiteral("m_poeMainSettingTab"));
        label_21 = new QLabel(m_poeMainSettingTab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(22, 23, 161, 16));
        m_numParticlesSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_numParticlesSpinBox->setObjectName(QStringLiteral("m_numParticlesSpinBox"));
        m_numParticlesSpinBox->setGeometry(QRect(200, 20, 91, 24));
        m_numParticlesSpinBox->setDecimals(0);
        m_numParticlesSpinBox->setMinimum(8);
        m_numParticlesSpinBox->setMaximum(1024);
        m_numParticlesSpinBox->setSingleStep(1);
        label_22 = new QLabel(m_poeMainSettingTab);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(22, 53, 161, 16));
        m_durationSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_durationSpinBox->setObjectName(QStringLiteral("m_durationSpinBox"));
        m_durationSpinBox->setGeometry(QRect(200, 50, 91, 24));
        m_durationSpinBox->setDecimals(0);
        m_durationSpinBox->setMinimum(0);
        m_durationSpinBox->setMaximum(65535);
        m_durationSpinBox->setSingleStep(1);
        label_23 = new QLabel(m_poeMainSettingTab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(22, 83, 161, 16));
        m_durationRanomnessSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_durationRanomnessSpinBox->setObjectName(QStringLiteral("m_durationRanomnessSpinBox"));
        m_durationRanomnessSpinBox->setGeometry(QRect(200, 80, 91, 24));
        m_durationRanomnessSpinBox->setDecimals(0);
        m_durationRanomnessSpinBox->setMinimum(0);
        m_durationRanomnessSpinBox->setMaximum(65535);
        m_durationRanomnessSpinBox->setSingleStep(1);
        label_24 = new QLabel(m_poeMainSettingTab);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(22, 113, 161, 16));
        m_velocitySensitivitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_velocitySensitivitySpinBox->setObjectName(QStringLiteral("m_velocitySensitivitySpinBox"));
        m_velocitySensitivitySpinBox->setGeometry(QRect(200, 110, 91, 24));
        m_velocitySensitivitySpinBox->setDecimals(0);
        m_velocitySensitivitySpinBox->setMinimum(0);
        m_velocitySensitivitySpinBox->setMaximum(65535);
        m_velocitySensitivitySpinBox->setSingleStep(1);
        m_minHorizontalVelocitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_minHorizontalVelocitySpinBox->setObjectName(QStringLiteral("m_minHorizontalVelocitySpinBox"));
        m_minHorizontalVelocitySpinBox->setGeometry(QRect(198, 147, 91, 24));
        m_minHorizontalVelocitySpinBox->setDecimals(0);
        m_minHorizontalVelocitySpinBox->setMinimum(0);
        m_minHorizontalVelocitySpinBox->setMaximum(65535);
        m_minHorizontalVelocitySpinBox->setSingleStep(1);
        label_25 = new QLabel(m_poeMainSettingTab);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(20, 150, 161, 16));
        m_maxHorizontalVelocitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_maxHorizontalVelocitySpinBox->setObjectName(QStringLiteral("m_maxHorizontalVelocitySpinBox"));
        m_maxHorizontalVelocitySpinBox->setGeometry(QRect(198, 177, 91, 24));
        m_maxHorizontalVelocitySpinBox->setDecimals(0);
        m_maxHorizontalVelocitySpinBox->setMinimum(0);
        m_maxHorizontalVelocitySpinBox->setMaximum(65535);
        m_maxHorizontalVelocitySpinBox->setSingleStep(1);
        label_26 = new QLabel(m_poeMainSettingTab);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(20, 180, 161, 16));
        m_minVerticalVelocitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_minVerticalVelocitySpinBox->setObjectName(QStringLiteral("m_minVerticalVelocitySpinBox"));
        m_minVerticalVelocitySpinBox->setGeometry(QRect(198, 207, 91, 24));
        m_minVerticalVelocitySpinBox->setDecimals(0);
        m_minVerticalVelocitySpinBox->setMinimum(0);
        m_minVerticalVelocitySpinBox->setMaximum(65535);
        m_minVerticalVelocitySpinBox->setSingleStep(1);
        label_27 = new QLabel(m_poeMainSettingTab);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 210, 161, 16));
        label_28 = new QLabel(m_poeMainSettingTab);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(22, 243, 161, 16));
        m_maxVerticalVelocitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_maxVerticalVelocitySpinBox->setObjectName(QStringLiteral("m_maxVerticalVelocitySpinBox"));
        m_maxVerticalVelocitySpinBox->setGeometry(QRect(200, 240, 91, 24));
        m_maxVerticalVelocitySpinBox->setDecimals(0);
        m_maxVerticalVelocitySpinBox->setMinimum(0);
        m_maxVerticalVelocitySpinBox->setMaximum(65535);
        m_maxVerticalVelocitySpinBox->setSingleStep(1);
        m_endVelocitySpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_endVelocitySpinBox->setObjectName(QStringLiteral("m_endVelocitySpinBox"));
        m_endVelocitySpinBox->setGeometry(QRect(198, 267, 91, 24));
        m_endVelocitySpinBox->setDecimals(0);
        m_endVelocitySpinBox->setMinimum(0);
        m_endVelocitySpinBox->setMaximum(65535);
        m_endVelocitySpinBox->setSingleStep(1);
        label_29 = new QLabel(m_poeMainSettingTab);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 270, 161, 16));
        m_gravityXSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_gravityXSpinBox->setObjectName(QStringLiteral("m_gravityXSpinBox"));
        m_gravityXSpinBox->setGeometry(QRect(40, 320, 71, 24));
        m_gravityXSpinBox->setDecimals(0);
        m_gravityXSpinBox->setMinimum(0);
        m_gravityXSpinBox->setMaximum(65535);
        m_gravityXSpinBox->setSingleStep(1);
        label_30 = new QLabel(m_poeMainSettingTab);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 300, 161, 16));
        label_31 = new QLabel(m_poeMainSettingTab);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(120, 320, 21, 16));
        m_gravityYSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_gravityYSpinBox->setObjectName(QStringLiteral("m_gravityYSpinBox"));
        m_gravityYSpinBox->setGeometry(QRect(140, 320, 71, 24));
        m_gravityYSpinBox->setDecimals(0);
        m_gravityYSpinBox->setMinimum(0);
        m_gravityYSpinBox->setMaximum(65535);
        m_gravityYSpinBox->setSingleStep(1);
        m_gravityZSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_gravityZSpinBox->setObjectName(QStringLiteral("m_gravityZSpinBox"));
        m_gravityZSpinBox->setGeometry(QRect(240, 320, 71, 24));
        m_gravityZSpinBox->setDecimals(0);
        m_gravityZSpinBox->setMinimum(0);
        m_gravityZSpinBox->setMaximum(65535);
        m_gravityZSpinBox->setSingleStep(1);
        label_32 = new QLabel(m_poeMainSettingTab);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(220, 320, 21, 16));
        label_33 = new QLabel(m_poeMainSettingTab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 320, 21, 16));
        label_34 = new QLabel(m_poeMainSettingTab);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(20, 360, 191, 16));
        m_sourceColorRSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceColorRSpinBox->setObjectName(QStringLiteral("m_sourceColorRSpinBox"));
        m_sourceColorRSpinBox->setGeometry(QRect(40, 390, 51, 24));
        m_sourceColorRSpinBox->setDecimals(0);
        m_sourceColorRSpinBox->setMinimum(0);
        m_sourceColorRSpinBox->setMaximum(65535);
        m_sourceColorRSpinBox->setSingleStep(1);
        m_sourceColorGSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceColorGSpinBox->setObjectName(QStringLiteral("m_sourceColorGSpinBox"));
        m_sourceColorGSpinBox->setGeometry(QRect(110, 390, 51, 24));
        m_sourceColorGSpinBox->setDecimals(0);
        m_sourceColorGSpinBox->setMinimum(0);
        m_sourceColorGSpinBox->setMaximum(65535);
        m_sourceColorGSpinBox->setSingleStep(1);
        m_sourceColorBSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceColorBSpinBox->setObjectName(QStringLiteral("m_sourceColorBSpinBox"));
        m_sourceColorBSpinBox->setGeometry(QRect(180, 390, 51, 24));
        m_sourceColorBSpinBox->setDecimals(0);
        m_sourceColorBSpinBox->setMinimum(0);
        m_sourceColorBSpinBox->setMaximum(65535);
        m_sourceColorBSpinBox->setSingleStep(1);
        m_sourceColorASpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceColorASpinBox->setObjectName(QStringLiteral("m_sourceColorASpinBox"));
        m_sourceColorASpinBox->setGeometry(QRect(250, 390, 51, 24));
        m_sourceColorASpinBox->setDecimals(0);
        m_sourceColorASpinBox->setMinimum(0);
        m_sourceColorASpinBox->setMaximum(65535);
        m_sourceColorASpinBox->setSingleStep(1);
        label_35 = new QLabel(m_poeMainSettingTab);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 390, 21, 16));
        label_36 = new QLabel(m_poeMainSettingTab);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(90, 390, 21, 16));
        label_37 = new QLabel(m_poeMainSettingTab);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(160, 390, 21, 16));
        label_38 = new QLabel(m_poeMainSettingTab);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(230, 390, 21, 16));
        label_39 = new QLabel(m_poeMainSettingTab);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(20, 460, 21, 16));
        label_40 = new QLabel(m_poeMainSettingTab);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(90, 460, 21, 16));
        m_destinationColorASpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationColorASpinBox->setObjectName(QStringLiteral("m_destinationColorASpinBox"));
        m_destinationColorASpinBox->setGeometry(QRect(250, 460, 51, 24));
        m_destinationColorASpinBox->setDecimals(0);
        m_destinationColorASpinBox->setMinimum(0);
        m_destinationColorASpinBox->setMaximum(65535);
        m_destinationColorASpinBox->setSingleStep(1);
        label_41 = new QLabel(m_poeMainSettingTab);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(230, 460, 21, 16));
        m_destinationColorBSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationColorBSpinBox->setObjectName(QStringLiteral("m_destinationColorBSpinBox"));
        m_destinationColorBSpinBox->setGeometry(QRect(180, 460, 51, 24));
        m_destinationColorBSpinBox->setDecimals(0);
        m_destinationColorBSpinBox->setMinimum(0);
        m_destinationColorBSpinBox->setMaximum(65535);
        m_destinationColorBSpinBox->setSingleStep(1);
        label_42 = new QLabel(m_poeMainSettingTab);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(160, 460, 21, 16));
        m_destinationColorGSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationColorGSpinBox->setObjectName(QStringLiteral("m_destinationColorGSpinBox"));
        m_destinationColorGSpinBox->setGeometry(QRect(110, 460, 51, 24));
        m_destinationColorGSpinBox->setDecimals(0);
        m_destinationColorGSpinBox->setMinimum(0);
        m_destinationColorGSpinBox->setMaximum(65535);
        m_destinationColorGSpinBox->setSingleStep(1);
        m_destinationColorRSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationColorRSpinBox->setObjectName(QStringLiteral("m_destinationColorRSpinBox"));
        m_destinationColorRSpinBox->setGeometry(QRect(40, 460, 51, 24));
        m_destinationColorRSpinBox->setDecimals(0);
        m_destinationColorRSpinBox->setMinimum(0);
        m_destinationColorRSpinBox->setMaximum(65535);
        m_destinationColorRSpinBox->setSingleStep(1);
        label_43 = new QLabel(m_poeMainSettingTab);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(20, 430, 161, 16));
        label_44 = new QLabel(m_poeMainSettingTab);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(20, 500, 161, 16));
        m_sourceSizeYSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceSizeYSpinBox->setObjectName(QStringLiteral("m_sourceSizeYSpinBox"));
        m_sourceSizeYSpinBox->setGeometry(QRect(140, 520, 71, 24));
        m_sourceSizeYSpinBox->setDecimals(0);
        m_sourceSizeYSpinBox->setMinimum(0);
        m_sourceSizeYSpinBox->setMaximum(65535);
        m_sourceSizeYSpinBox->setSingleStep(1);
        label_45 = new QLabel(m_poeMainSettingTab);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(120, 520, 21, 16));
        label_46 = new QLabel(m_poeMainSettingTab);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 520, 21, 16));
        m_sourceSizeXSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_sourceSizeXSpinBox->setObjectName(QStringLiteral("m_sourceSizeXSpinBox"));
        m_sourceSizeXSpinBox->setGeometry(QRect(40, 520, 71, 24));
        m_sourceSizeXSpinBox->setDecimals(0);
        m_sourceSizeXSpinBox->setMinimum(0);
        m_sourceSizeXSpinBox->setMaximum(65535);
        m_sourceSizeXSpinBox->setSingleStep(1);
        m_destinationSizeXSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationSizeXSpinBox->setObjectName(QStringLiteral("m_destinationSizeXSpinBox"));
        m_destinationSizeXSpinBox->setGeometry(QRect(40, 580, 71, 24));
        m_destinationSizeXSpinBox->setDecimals(0);
        m_destinationSizeXSpinBox->setMinimum(0);
        m_destinationSizeXSpinBox->setMaximum(65535);
        m_destinationSizeXSpinBox->setSingleStep(1);
        label_47 = new QLabel(m_poeMainSettingTab);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(20, 560, 161, 16));
        label_48 = new QLabel(m_poeMainSettingTab);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(120, 580, 21, 16));
        label_49 = new QLabel(m_poeMainSettingTab);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(20, 580, 21, 16));
        m_destinationSizeYSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_destinationSizeYSpinBox->setObjectName(QStringLiteral("m_destinationSizeYSpinBox"));
        m_destinationSizeYSpinBox->setGeometry(QRect(140, 580, 71, 24));
        m_destinationSizeYSpinBox->setDecimals(0);
        m_destinationSizeYSpinBox->setMinimum(0);
        m_destinationSizeYSpinBox->setMaximum(65535);
        m_destinationSizeYSpinBox->setSingleStep(1);
        m_minEmittIntervalSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_minEmittIntervalSpinBox->setObjectName(QStringLiteral("m_minEmittIntervalSpinBox"));
        m_minEmittIntervalSpinBox->setGeometry(QRect(198, 627, 91, 24));
        m_minEmittIntervalSpinBox->setDecimals(0);
        m_minEmittIntervalSpinBox->setMinimum(0);
        m_minEmittIntervalSpinBox->setMaximum(65535);
        m_minEmittIntervalSpinBox->setSingleStep(1);
        label_50 = new QLabel(m_poeMainSettingTab);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(20, 630, 161, 16));
        label_51 = new QLabel(m_poeMainSettingTab);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(22, 673, 161, 16));
        m_maxEmittIntervalSpinBox = new QDoubleSpinBox(m_poeMainSettingTab);
        m_maxEmittIntervalSpinBox->setObjectName(QStringLiteral("m_maxEmittIntervalSpinBox"));
        m_maxEmittIntervalSpinBox->setGeometry(QRect(200, 670, 91, 24));
        m_maxEmittIntervalSpinBox->setDecimals(0);
        m_maxEmittIntervalSpinBox->setMinimum(0);
        m_maxEmittIntervalSpinBox->setMaximum(65535);
        m_maxEmittIntervalSpinBox->setSingleStep(1);
        m_poeSettingsTab->addTab(m_poeMainSettingTab, QString());
        m_poeMaterialsSettingTab = new QWidget();
        m_poeMaterialsSettingTab->setObjectName(QStringLiteral("m_poeMaterialsSettingTab"));
        m_poeMaterialsSettingTab->setEnabled(true);
        m_poeMaterialsSettingTab->setFont(font4);
        m_materialsComboBox_2 = new QComboBox(m_poeMaterialsSettingTab);
        m_materialsComboBox_2->setObjectName(QStringLiteral("m_materialsComboBox_2"));
        m_materialsComboBox_2->setGeometry(QRect(20, 60, 280, 26));
        m_cullFaceCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_cullFaceCheckBox_2->setObjectName(QStringLiteral("m_cullFaceCheckBox_2"));
        m_cullFaceCheckBox_2->setGeometry(QRect(20, 120, 271, 20));
        m_cullModeComboBox_2 = new QComboBox(m_poeMaterialsSettingTab);
        m_cullModeComboBox_2->setObjectName(QStringLiteral("m_cullModeComboBox_2"));
        m_cullModeComboBox_2->setGeometry(QRect(118, 146, 182, 26));
        m_depthTestCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_depthTestCheckBox_2->setObjectName(QStringLiteral("m_depthTestCheckBox_2"));
        m_depthTestCheckBox_2->setGeometry(QRect(20, 180, 271, 20));
        m_depthMaskCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_depthMaskCheckBox_2->setObjectName(QStringLiteral("m_depthMaskCheckBox_2"));
        m_depthMaskCheckBox_2->setGeometry(QRect(20, 200, 271, 20));
        m_blendingCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_blendingCheckBox_2->setObjectName(QStringLiteral("m_blendingCheckBox_2"));
        m_blendingCheckBox_2->setGeometry(QRect(20, 220, 271, 20));
        m_blendingSourceComboBox_2 = new QComboBox(m_poeMaterialsSettingTab);
        m_blendingSourceComboBox_2->setObjectName(QStringLiteral("m_blendingSourceComboBox_2"));
        m_blendingSourceComboBox_2->setGeometry(QRect(118, 246, 182, 26));
        m_blendingDesinationComboBox_2 = new QComboBox(m_poeMaterialsSettingTab);
        m_blendingDesinationComboBox_2->setObjectName(QStringLiteral("m_blendingDesinationComboBox_2"));
        m_blendingDesinationComboBox_2->setGeometry(QRect(118, 276, 182, 26));
        label_14 = new QLabel(m_poeMaterialsSettingTab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(22, 150, 62, 16));
        label_15 = new QLabel(m_poeMaterialsSettingTab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(22, 250, 62, 16));
        label_16 = new QLabel(m_poeMaterialsSettingTab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 280, 91, 16));
        m_clippingCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_clippingCheckBox_2->setObjectName(QStringLiteral("m_clippingCheckBox_2"));
        m_clippingCheckBox_2->setGeometry(QRect(20, 310, 271, 20));
        m_clippingXSpinBox_2 = new QDoubleSpinBox(m_poeMaterialsSettingTab);
        m_clippingXSpinBox_2->setObjectName(QStringLiteral("m_clippingXSpinBox_2"));
        m_clippingXSpinBox_2->setGeometry(QRect(40, 337, 70, 24));
        m_clippingXSpinBox_2->setMinimum(-1);
        m_clippingXSpinBox_2->setMaximum(1);
        m_clippingXSpinBox_2->setSingleStep(0.1);
        m_clippingYSpinBox_2 = new QDoubleSpinBox(m_poeMaterialsSettingTab);
        m_clippingYSpinBox_2->setObjectName(QStringLiteral("m_clippingYSpinBox_2"));
        m_clippingYSpinBox_2->setGeometry(QRect(136, 337, 70, 24));
        m_clippingYSpinBox_2->setMinimum(-1);
        m_clippingYSpinBox_2->setMaximum(1);
        m_clippingYSpinBox_2->setSingleStep(0.1);
        m_clippingZSpinBox_2 = new QDoubleSpinBox(m_poeMaterialsSettingTab);
        m_clippingZSpinBox_2->setObjectName(QStringLiteral("m_clippingZSpinBox_2"));
        m_clippingZSpinBox_2->setGeometry(QRect(230, 337, 70, 24));
        m_clippingZSpinBox_2->setMinimum(-1);
        m_clippingZSpinBox_2->setMaximum(1);
        m_clippingZSpinBox_2->setSingleStep(0.1);
        m_clippingWSpinBox_2 = new QDoubleSpinBox(m_poeMaterialsSettingTab);
        m_clippingWSpinBox_2->setObjectName(QStringLiteral("m_clippingWSpinBox_2"));
        m_clippingWSpinBox_2->setGeometry(QRect(136, 367, 70, 24));
        m_clippingWSpinBox_2->setMinimum(-1024);
        m_clippingWSpinBox_2->setMaximum(1024);
        m_clippingWSpinBox_2->setSingleStep(0.1);
        label_17 = new QLabel(m_poeMaterialsSettingTab);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(22, 340, 18, 16));
        label_18 = new QLabel(m_poeMaterialsSettingTab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(120, 340, 18, 16));
        label_19 = new QLabel(m_poeMaterialsSettingTab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(214, 340, 18, 16));
        label_20 = new QLabel(m_poeMaterialsSettingTab);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(120, 370, 18, 16));
        m_reflectingCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_reflectingCheckBox_2->setObjectName(QStringLiteral("m_reflectingCheckBox_2"));
        m_reflectingCheckBox_2->setGeometry(QRect(20, 400, 271, 20));
        m_shadowingCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_shadowingCheckBox_2->setObjectName(QStringLiteral("m_shadowingCheckBox_2"));
        m_shadowingCheckBox_2->setGeometry(QRect(20, 420, 271, 20));
        m_debuggingCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_debuggingCheckBox_2->setObjectName(QStringLiteral("m_debuggingCheckBox_2"));
        m_debuggingCheckBox_2->setGeometry(QRect(20, 440, 271, 20));
        m_shaderButton_2 = new QPushButton(m_poeMaterialsSettingTab);
        m_shaderButton_2->setObjectName(QStringLiteral("m_shaderButton_2"));
        m_shaderButton_2->setGeometry(QRect(13, 470, 291, 24));
        m_texture1LoadButton_2 = new QPushButton(m_poeMaterialsSettingTab);
        m_texture1LoadButton_2->setObjectName(QStringLiteral("m_texture1LoadButton_2"));
        m_texture1LoadButton_2->setGeometry(QRect(20, 600, 64, 24));
        m_texture1LoadButton_2->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_5 = new QLabel(m_poeMaterialsSettingTab);
        m_texture01Label_5->setObjectName(QStringLiteral("m_texture01Label_5"));
        m_texture01Label_5->setGeometry(QRect(10, 510, 81, 16));
        m_texture01Label_5->setFont(font1);
        m_texture01Label_5->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture1Image_2 = new QLabel(m_poeMaterialsSettingTab);
        m_texture1Image_2->setObjectName(QStringLiteral("m_texture1Image_2"));
        m_texture1Image_2->setGeometry(QRect(20, 530, 64, 64));
        m_texture1Image_2->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture1Image_2->setFrameShape(QFrame::Box);
        m_texture1Image_2->setScaledContents(true);
        m_texture1Image_2->setAlignment(Qt::AlignCenter);
        m_texture01Label_6 = new QLabel(m_poeMaterialsSettingTab);
        m_texture01Label_6->setObjectName(QStringLiteral("m_texture01Label_6"));
        m_texture01Label_6->setGeometry(QRect(100, 510, 81, 16));
        m_texture01Label_6->setFont(font1);
        m_texture01Label_6->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture2Image_2 = new QLabel(m_poeMaterialsSettingTab);
        m_texture2Image_2->setObjectName(QStringLiteral("m_texture2Image_2"));
        m_texture2Image_2->setGeometry(QRect(110, 530, 64, 64));
        m_texture2Image_2->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture2Image_2->setFrameShape(QFrame::Box);
        m_texture2Image_2->setScaledContents(true);
        m_texture2Image_2->setAlignment(Qt::AlignCenter);
        m_texture2LoadButton_2 = new QPushButton(m_poeMaterialsSettingTab);
        m_texture2LoadButton_2->setObjectName(QStringLiteral("m_texture2LoadButton_2"));
        m_texture2LoadButton_2->setGeometry(QRect(110, 600, 64, 24));
        m_texture2LoadButton_2->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_7 = new QLabel(m_poeMaterialsSettingTab);
        m_texture01Label_7->setObjectName(QStringLiteral("m_texture01Label_7"));
        m_texture01Label_7->setGeometry(QRect(190, 510, 81, 16));
        m_texture01Label_7->setFont(font1);
        m_texture01Label_7->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture3Image_2 = new QLabel(m_poeMaterialsSettingTab);
        m_texture3Image_2->setObjectName(QStringLiteral("m_texture3Image_2"));
        m_texture3Image_2->setGeometry(QRect(200, 530, 64, 64));
        m_texture3Image_2->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture3Image_2->setFrameShape(QFrame::Box);
        m_texture3Image_2->setScaledContents(true);
        m_texture3Image_2->setAlignment(Qt::AlignCenter);
        m_texture3LoadButton_2 = new QPushButton(m_poeMaterialsSettingTab);
        m_texture3LoadButton_2->setObjectName(QStringLiteral("m_texture3LoadButton_2"));
        m_texture3LoadButton_2->setGeometry(QRect(200, 600, 64, 24));
        m_texture3LoadButton_2->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_materialEnabledCheckBox_2 = new QCheckBox(m_poeMaterialsSettingTab);
        m_materialEnabledCheckBox_2->setObjectName(QStringLiteral("m_materialEnabledCheckBox_2"));
        m_materialEnabledCheckBox_2->setGeometry(QRect(20, 90, 271, 20));
        m_drawCurrentRadioButton_2 = new QRadioButton(m_poeMaterialsSettingTab);
        m_drawCurrentRadioButton_2->setObjectName(QStringLiteral("m_drawCurrentRadioButton_2"));
        m_drawCurrentRadioButton_2->setGeometry(QRect(22, 30, 141, 20));
        m_drawAllRadioButton_2 = new QRadioButton(m_poeMaterialsSettingTab);
        m_drawAllRadioButton_2->setObjectName(QStringLiteral("m_drawAllRadioButton_2"));
        m_drawAllRadioButton_2->setGeometry(QRect(170, 30, 131, 20));
        m_poeSettingsTab->addTab(m_poeMaterialsSettingTab, QString());
        m_mainMenuTabs->addTab(m_particlesTab, QString());
        CMainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(CMainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1280, 22));
        CMainWindow->setMenuBar(menuBar);

        retranslateUi(CMainWindow);

        m_mainMenuTabs->setCurrentIndex(2);
        m_landscapePropertiesTab->setCurrentIndex(2);
        m_goeSettingsTab->setCurrentIndex(0);
        m_poeSettingsTab->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(CMainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *CMainWindow)
    {
        CMainWindow->setWindowTitle(QApplication::translate("CMainWindow", "indieEngine3D MapEditor", 0));
        generateGroupBox->setTitle(QApplication::translate("CMainWindow", "Generate", 0));
        label->setText(QApplication::translate("CMainWindow", "Frequency[0.1 .. 64.0]:", 0));
        label_2->setText(QApplication::translate("CMainWindow", "Octaves[1 .. 16]:", 0));
        label_3->setText(QApplication::translate("CMainWindow", "Seed:", 0));
        generateButton->setText(QApplication::translate("CMainWindow", "Generate", 0));
        label_4->setText(QApplication::translate("CMainWindow", "Size[64 .. 512]:", 0));
        label_5->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_6->setText(QApplication::translate("CMainWindow", "y:", 0));
        editGroupBox->setTitle(QApplication::translate("CMainWindow", "Edit", 0));
        m_falloffLabel->setText(QApplication::translate("CMainWindow", "Falloff Coefficient:", 0));
        m_brushSizeLabel->setText(QApplication::translate("CMainWindow", "Brush Size:", 0));
        m_smoothLabel->setText(QApplication::translate("CMainWindow", "Smooth Coefficient:", 0));
        m_brushStrengthLabel->setText(QApplication::translate("CMainWindow", "Brush Strength:", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(m_landscapeHeightmapTab), QApplication::translate("CMainWindow", "Landscape", 0));
        m_texture01Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture01Label->setText(QApplication::translate("CMainWindow", "Texture sampler 1:", 0));
        m_texture02Label->setText(QApplication::translate("CMainWindow", "Texture sampler 2:", 0));
        m_texture02Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture03Label->setText(QApplication::translate("CMainWindow", "Texture sampler 3:", 0));
        m_texture03Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture01Img->setText(QString());
        m_texture02Img->setText(QString());
        m_texture03Img->setText(QString());
        m_textureTilling01Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_textureTilling02Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_textureTilling03Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(m_landscapeTexturesTab), QApplication::translate("CMainWindow", "Textures", 0));
        m_addModelToSceneButton->setText(QApplication::translate("CMainWindow", "Add To Scene...", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(m_landscapeGameobjectsTab), QApplication::translate("CMainWindow", "Models", 0));
        m_heightmapGenerationStatisticLabel->setText(QApplication::translate("CMainWindow", "Generation Statistics", 0));
        m_mainMenuTabs->setTabText(m_mainMenuTabs->indexOf(m_sceneTab), QApplication::translate("CMainWindow", "Scene", 0));
        m_createGameObjectConfiguration->setText(QApplication::translate("CMainWindow", "Create configuration...", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeMainSettingTab), QApplication::translate("CMainWindow", "Configuration", 0));
        m_cullFaceCheckBox->setText(QApplication::translate("CMainWindow", "  Cull Face", 0));
        m_depthTestCheckBox->setText(QApplication::translate("CMainWindow", "  Depth Test", 0));
        m_depthMaskCheckBox->setText(QApplication::translate("CMainWindow", "  Depth Mask", 0));
        m_blendingCheckBox->setText(QApplication::translate("CMainWindow", "  Blending", 0));
        label_7->setText(QApplication::translate("CMainWindow", "Mode:", 0));
        label_8->setText(QApplication::translate("CMainWindow", "Source:", 0));
        label_9->setText(QApplication::translate("CMainWindow", "Destination:", 0));
        m_clippingCheckBox->setText(QApplication::translate("CMainWindow", "  Clipping", 0));
        label_10->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_11->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_12->setText(QApplication::translate("CMainWindow", "z:", 0));
        label_13->setText(QApplication::translate("CMainWindow", "w:", 0));
        m_reflectingCheckBox->setText(QApplication::translate("CMainWindow", "  Reflecting", 0));
        m_shadowingCheckBox->setText(QApplication::translate("CMainWindow", "  Shadowing", 0));
        m_debuggingCheckBox->setText(QApplication::translate("CMainWindow", "  Debugging", 0));
        m_shaderButton->setText(QApplication::translate("CMainWindow", "Shader...", 0));
        m_texture1LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_2->setText(QApplication::translate("CMainWindow", "Texture 1:", 0));
        m_texture1Image->setText(QString());
        m_texture01Label_3->setText(QApplication::translate("CMainWindow", "Texture 2:", 0));
        m_texture2Image->setText(QString());
        m_texture2LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_4->setText(QApplication::translate("CMainWindow", "Texture 3:", 0));
        m_texture3Image->setText(QString());
        m_texture3LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_materialEnabledCheckBox->setText(QApplication::translate("CMainWindow", "  Enabled", 0));
        m_drawCurrentRadioButton->setText(QApplication::translate("CMainWindow", "Draw Current", 0));
        m_drawAllRadioButton->setText(QApplication::translate("CMainWindow", "Draw All", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeMaterialsSettingTab), QApplication::translate("CMainWindow", "Materials", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeAnimationsSettingTab), QApplication::translate("CMainWindow", "Animations", 0));
        m_mainMenuTabs->setTabText(m_mainMenuTabs->indexOf(m_gameObjectTab), QApplication::translate("CMainWindow", "Game Object", 0));
        label_21->setText(QApplication::translate("CMainWindow", "Num Particles:", 0));
        label_22->setText(QApplication::translate("CMainWindow", "Duration:", 0));
        label_23->setText(QApplication::translate("CMainWindow", "Duration Randomness:", 0));
        label_24->setText(QApplication::translate("CMainWindow", "Velocity Sensitivity:", 0));
        label_25->setText(QApplication::translate("CMainWindow", "Min Horizontal Velocity:", 0));
        label_26->setText(QApplication::translate("CMainWindow", "Max Horizontal Velocity:", 0));
        label_27->setText(QApplication::translate("CMainWindow", "Min Vertical Velocity:", 0));
        label_28->setText(QApplication::translate("CMainWindow", "Max Vertical Velocity:", 0));
        label_29->setText(QApplication::translate("CMainWindow", "End Velocity:", 0));
        label_30->setText(QApplication::translate("CMainWindow", "Gravity:", 0));
        label_31->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_32->setText(QApplication::translate("CMainWindow", "z:", 0));
        label_33->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_34->setText(QApplication::translate("CMainWindow", "Source Color:", 0));
        label_35->setText(QApplication::translate("CMainWindow", "r:", 0));
        label_36->setText(QApplication::translate("CMainWindow", "g:", 0));
        label_37->setText(QApplication::translate("CMainWindow", "b:", 0));
        label_38->setText(QApplication::translate("CMainWindow", "a:", 0));
        label_39->setText(QApplication::translate("CMainWindow", "r:", 0));
        label_40->setText(QApplication::translate("CMainWindow", "g:", 0));
        label_41->setText(QApplication::translate("CMainWindow", "a:", 0));
        label_42->setText(QApplication::translate("CMainWindow", "b:", 0));
        label_43->setText(QApplication::translate("CMainWindow", "Destination Color:", 0));
        label_44->setText(QApplication::translate("CMainWindow", "Source Size:", 0));
        label_45->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_46->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_47->setText(QApplication::translate("CMainWindow", "Destination Size:", 0));
        label_48->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_49->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_50->setText(QApplication::translate("CMainWindow", "Min Emitt Interval:", 0));
        label_51->setText(QApplication::translate("CMainWindow", "Max Emitt Interval:", 0));
        m_poeSettingsTab->setTabText(m_poeSettingsTab->indexOf(m_poeMainSettingTab), QApplication::translate("CMainWindow", "Configuration", 0));
        m_cullFaceCheckBox_2->setText(QApplication::translate("CMainWindow", "  Cull Face", 0));
        m_depthTestCheckBox_2->setText(QApplication::translate("CMainWindow", "  Depth Test", 0));
        m_depthMaskCheckBox_2->setText(QApplication::translate("CMainWindow", "  Depth Mask", 0));
        m_blendingCheckBox_2->setText(QApplication::translate("CMainWindow", "  Blending", 0));
        label_14->setText(QApplication::translate("CMainWindow", "Mode:", 0));
        label_15->setText(QApplication::translate("CMainWindow", "Source:", 0));
        label_16->setText(QApplication::translate("CMainWindow", "Destination:", 0));
        m_clippingCheckBox_2->setText(QApplication::translate("CMainWindow", "  Clipping", 0));
        label_17->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_18->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_19->setText(QApplication::translate("CMainWindow", "z:", 0));
        label_20->setText(QApplication::translate("CMainWindow", "w:", 0));
        m_reflectingCheckBox_2->setText(QApplication::translate("CMainWindow", "  Reflecting", 0));
        m_shadowingCheckBox_2->setText(QApplication::translate("CMainWindow", "  Shadowing", 0));
        m_debuggingCheckBox_2->setText(QApplication::translate("CMainWindow", "  Debugging", 0));
        m_shaderButton_2->setText(QApplication::translate("CMainWindow", "Shader...", 0));
        m_texture1LoadButton_2->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_5->setText(QApplication::translate("CMainWindow", "Texture 1:", 0));
        m_texture1Image_2->setText(QString());
        m_texture01Label_6->setText(QApplication::translate("CMainWindow", "Texture 2:", 0));
        m_texture2Image_2->setText(QString());
        m_texture2LoadButton_2->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_7->setText(QApplication::translate("CMainWindow", "Texture 3:", 0));
        m_texture3Image_2->setText(QString());
        m_texture3LoadButton_2->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_materialEnabledCheckBox_2->setText(QApplication::translate("CMainWindow", "  Enabled", 0));
        m_drawCurrentRadioButton_2->setText(QApplication::translate("CMainWindow", "Draw Current", 0));
        m_drawAllRadioButton_2->setText(QApplication::translate("CMainWindow", "Draw All", 0));
        m_poeSettingsTab->setTabText(m_poeSettingsTab->indexOf(m_poeMaterialsSettingTab), QApplication::translate("CMainWindow", "Materials", 0));
        m_mainMenuTabs->setTabText(m_mainMenuTabs->indexOf(m_particlesTab), QApplication::translate("CMainWindow", "Particles", 0));
    } // retranslateUi

};

namespace Ui {
    class CMainWindow: public Ui_CMainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CMAINWINDOW_H
