/********************************************************************************
** Form generated from reading UI file 'CMainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CMAINWINDOW_H
#define UI_CMAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CMainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *m_mainMenuTabs;
    QWidget *sceneTab;
    QTabWidget *m_landscapePropertiesTab;
    QWidget *landscape_heightmap;
    QGroupBox *generateGroupBox;
    QSpinBox *m_octavesSpinBox;
    QLabel *label;
    QDoubleSpinBox *m_frequencySpinBox;
    QLabel *label_2;
    QLabel *label_3;
    QSpinBox *m_seedSpinBox;
    QPushButton *generateButton;
    QLabel *label_4;
    QSpinBox *m_sizeXSpinBox;
    QLabel *label_5;
    QLabel *label_6;
    QSpinBox *m_sizeYSpinBox;
    QGroupBox *editGroupBox;
    QSlider *m_smoothSlider;
    QSlider *m_brushSizeSlider;
    QLabel *m_falloffLabel;
    QLabel *m_brushSizeLabel;
    QLabel *m_smoothLabel;
    QSlider *m_brushStrengthSlider;
    QLabel *m_brushStrengthLabel;
    QSlider *m_falloffSlider;
    QWidget *landscape_textures;
    QPushButton *m_texture01Btn;
    QLabel *m_texture01Label;
    QLabel *m_texture02Label;
    QPushButton *m_texture02Btn;
    QLabel *m_texture03Label;
    QPushButton *m_texture03Btn;
    QLabel *m_texture01Img;
    QLabel *m_texture02Img;
    QLabel *m_texture03Img;
    QSpinBox *m_textureTilling01SpinBox;
    QLabel *m_textureTilling01Label;
    QLabel *m_textureTilling02Label;
    QSpinBox *m_textureTilling02SpinBox;
    QLabel *m_textureTilling03Label;
    QSpinBox *m_textureTilling03SpinBox;
    QWidget *models;
    QWidget *m_modelsOpenGLView;
    QWidget *m_oglWindow;
    QWidget *gameObjectTab;
    QWidget *m_gameObjectGLWindow;
    QTabWidget *m_goeSettingsTab;
    QWidget *m_goeMainSettingTab;
    QPushButton *m_createGameObjectConfiguration;
    QWidget *m_goeMaterialsSettingTab;
    QComboBox *m_materialsComboBox;
    QCheckBox *m_cullFaceCheckBox;
    QComboBox *m_cullModeComboBox;
    QCheckBox *m_depthTestCheckBox;
    QCheckBox *m_depthMaskCheckBox;
    QCheckBox *m_blendingCheckBox;
    QComboBox *m_blendingSourceComboBox;
    QComboBox *m_blendingDesinationComboBox;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QCheckBox *m_clippingCheckBox;
    QDoubleSpinBox *m_clippingXSpinBox;
    QDoubleSpinBox *m_clippingYSpinBox;
    QDoubleSpinBox *m_clippingZSpinBox;
    QDoubleSpinBox *m_clippingWSpinBox;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QCheckBox *m_reflectingCheckBox;
    QCheckBox *m_shadowingCheckBox;
    QCheckBox *m_debuggingCheckBox;
    QPushButton *m_shaderButton;
    QPushButton *m_texture1LoadButton;
    QLabel *m_texture01Label_2;
    QLabel *m_texture1Image;
    QLabel *m_texture01Label_3;
    QLabel *m_texture2Image;
    QPushButton *m_texture2LoadButton;
    QLabel *m_texture01Label_4;
    QLabel *m_texture3Image;
    QPushButton *m_texture3LoadButton;
    QWidget *m_goeAnimationsSettingTab;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *CMainWindow)
    {
        if (CMainWindow->objectName().isEmpty())
            CMainWindow->setObjectName(QStringLiteral("CMainWindow"));
        CMainWindow->resize(1280, 800);
        CMainWindow->setMinimumSize(QSize(1280, 800));
        CMainWindow->setMaximumSize(QSize(1280, 800));
        CMainWindow->setStyleSheet(QStringLiteral("background-color: rgb(128, 128, 128);"));
        centralWidget = new QWidget(CMainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setStyleSheet(QStringLiteral("background-color: rgb(64, 64, 64);"));
        m_mainMenuTabs = new QTabWidget(centralWidget);
        m_mainMenuTabs->setObjectName(QStringLiteral("m_mainMenuTabs"));
        m_mainMenuTabs->setGeometry(QRect(-1, -1, 1281, 781));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(64, 64, 64, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        m_mainMenuTabs->setPalette(palette);
        QFont font;
        font.setFamily(QStringLiteral("Menlo"));
        font.setPointSize(13);
        font.setBold(false);
        font.setWeight(50);
        m_mainMenuTabs->setFont(font);
        m_mainMenuTabs->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_mainMenuTabs->setDocumentMode(true);
        m_mainMenuTabs->setMovable(true);
        sceneTab = new QWidget();
        sceneTab->setObjectName(QStringLiteral("sceneTab"));
        m_landscapePropertiesTab = new QTabWidget(sceneTab);
        m_landscapePropertiesTab->setObjectName(QStringLiteral("m_landscapePropertiesTab"));
        m_landscapePropertiesTab->setGeometry(QRect(930, -4, 350, 760));
        m_landscapePropertiesTab->setFont(font);
        m_landscapePropertiesTab->setStyleSheet(QStringLiteral("background-color: rgb(64, 64, 64);"));
        m_landscapePropertiesTab->setTabPosition(QTabWidget::West);
        m_landscapePropertiesTab->setTabShape(QTabWidget::Rounded);
        m_landscapePropertiesTab->setDocumentMode(true);
        m_landscapePropertiesTab->setMovable(true);
        landscape_heightmap = new QWidget();
        landscape_heightmap->setObjectName(QStringLiteral("landscape_heightmap"));
        generateGroupBox = new QGroupBox(landscape_heightmap);
        generateGroupBox->setObjectName(QStringLiteral("generateGroupBox"));
        generateGroupBox->setGeometry(QRect(10, 270, 301, 321));
        QFont font1;
        font1.setFamily(QStringLiteral("Menlo"));
        font1.setBold(true);
        font1.setWeight(75);
        generateGroupBox->setFont(font1);
        generateGroupBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_octavesSpinBox = new QSpinBox(generateGroupBox);
        m_octavesSpinBox->setObjectName(QStringLiteral("m_octavesSpinBox"));
        m_octavesSpinBox->setGeometry(QRect(160, 100, 81, 24));
        m_octavesSpinBox->setMinimum(1);
        m_octavesSpinBox->setMaximum(16);
        label = new QLabel(generateGroupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 30, 191, 16));
        label->setFont(font1);
        m_frequencySpinBox = new QDoubleSpinBox(generateGroupBox);
        m_frequencySpinBox->setObjectName(QStringLiteral("m_frequencySpinBox"));
        m_frequencySpinBox->setGeometry(QRect(160, 50, 81, 24));
        m_frequencySpinBox->setDecimals(1);
        m_frequencySpinBox->setMinimum(0.1);
        m_frequencySpinBox->setMaximum(64);
        m_frequencySpinBox->setSingleStep(0.1);
        label_2 = new QLabel(generateGroupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 80, 191, 16));
        label_2->setFont(font1);
        label_3 = new QLabel(generateGroupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 130, 191, 16));
        label_3->setFont(font1);
        m_seedSpinBox = new QSpinBox(generateGroupBox);
        m_seedSpinBox->setObjectName(QStringLiteral("m_seedSpinBox"));
        m_seedSpinBox->setGeometry(QRect(160, 150, 81, 24));
        m_seedSpinBox->setMaximum(65535);
        m_seedSpinBox->setValue(65535);
        generateButton = new QPushButton(generateGroupBox);
        generateButton->setObjectName(QStringLiteral("generateButton"));
        generateButton->setGeometry(QRect(23, 280, 201, 32));
        generateButton->setFont(font1);
        label_4 = new QLabel(generateGroupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 190, 191, 16));
        label_4->setFont(font1);
        m_sizeXSpinBox = new QSpinBox(generateGroupBox);
        m_sizeXSpinBox->setObjectName(QStringLiteral("m_sizeXSpinBox"));
        m_sizeXSpinBox->setGeometry(QRect(160, 220, 81, 24));
        m_sizeXSpinBox->setMinimum(64);
        m_sizeXSpinBox->setMaximum(512);
        m_sizeXSpinBox->setSingleStep(64);
        m_sizeXSpinBox->setValue(512);
        label_5 = new QLabel(generateGroupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(120, 220, 31, 16));
        label_5->setFont(font1);
        label_6 = new QLabel(generateGroupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(120, 250, 31, 16));
        label_6->setFont(font1);
        m_sizeYSpinBox = new QSpinBox(generateGroupBox);
        m_sizeYSpinBox->setObjectName(QStringLiteral("m_sizeYSpinBox"));
        m_sizeYSpinBox->setGeometry(QRect(160, 250, 81, 24));
        m_sizeYSpinBox->setMinimum(64);
        m_sizeYSpinBox->setMaximum(512);
        m_sizeYSpinBox->setSingleStep(64);
        m_sizeYSpinBox->setValue(512);
        editGroupBox = new QGroupBox(landscape_heightmap);
        editGroupBox->setObjectName(QStringLiteral("editGroupBox"));
        editGroupBox->setGeometry(QRect(10, 10, 301, 251));
        QFont font2;
        font2.setFamily(QStringLiteral("Menlo"));
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setWeight(75);
        editGroupBox->setFont(font2);
        editGroupBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_smoothSlider = new QSlider(editGroupBox);
        m_smoothSlider->setObjectName(QStringLiteral("m_smoothSlider"));
        m_smoothSlider->setGeometry(QRect(40, 200, 225, 22));
        m_smoothSlider->setMaximum(3);
        m_smoothSlider->setOrientation(Qt::Horizontal);
        m_smoothSlider->setInvertedAppearance(false);
        m_smoothSlider->setInvertedControls(false);
        m_smoothSlider->setTickPosition(QSlider::TicksAbove);
        m_smoothSlider->setTickInterval(1);
        m_brushSizeSlider = new QSlider(editGroupBox);
        m_brushSizeSlider->setObjectName(QStringLiteral("m_brushSizeSlider"));
        m_brushSizeSlider->setGeometry(QRect(40, 50, 225, 22));
        m_brushSizeSlider->setMinimum(4);
        m_brushSizeSlider->setMaximum(32);
        m_brushSizeSlider->setSingleStep(2);
        m_brushSizeSlider->setOrientation(Qt::Horizontal);
        m_brushSizeSlider->setTickPosition(QSlider::TicksAbove);
        m_brushSizeSlider->setTickInterval(2);
        m_falloffLabel = new QLabel(editGroupBox);
        m_falloffLabel->setObjectName(QStringLiteral("m_falloffLabel"));
        m_falloffLabel->setGeometry(QRect(40, 130, 225, 20));
        m_falloffLabel->setFont(font2);
        m_brushSizeLabel = new QLabel(editGroupBox);
        m_brushSizeLabel->setObjectName(QStringLiteral("m_brushSizeLabel"));
        m_brushSizeLabel->setGeometry(QRect(40, 30, 225, 20));
        m_brushSizeLabel->setFont(font2);
        m_smoothLabel = new QLabel(editGroupBox);
        m_smoothLabel->setObjectName(QStringLiteral("m_smoothLabel"));
        m_smoothLabel->setGeometry(QRect(40, 180, 225, 20));
        m_smoothLabel->setFont(font2);
        m_brushStrengthSlider = new QSlider(editGroupBox);
        m_brushStrengthSlider->setObjectName(QStringLiteral("m_brushStrengthSlider"));
        m_brushStrengthSlider->setGeometry(QRect(40, 100, 225, 22));
        m_brushStrengthSlider->setMinimum(1);
        m_brushStrengthSlider->setMaximum(10);
        m_brushStrengthSlider->setOrientation(Qt::Horizontal);
        m_brushStrengthSlider->setTickPosition(QSlider::TicksAbove);
        m_brushStrengthSlider->setTickInterval(1);
        m_brushStrengthLabel = new QLabel(editGroupBox);
        m_brushStrengthLabel->setObjectName(QStringLiteral("m_brushStrengthLabel"));
        m_brushStrengthLabel->setGeometry(QRect(40, 80, 225, 20));
        m_brushStrengthLabel->setFont(font2);
        m_falloffSlider = new QSlider(editGroupBox);
        m_falloffSlider->setObjectName(QStringLiteral("m_falloffSlider"));
        m_falloffSlider->setGeometry(QRect(40, 150, 225, 22));
        m_falloffSlider->setOrientation(Qt::Horizontal);
        m_falloffSlider->setTickPosition(QSlider::TicksAbove);
        m_falloffSlider->setTickInterval(10);
        m_landscapePropertiesTab->addTab(landscape_heightmap, QString());
        landscape_textures = new QWidget();
        landscape_textures->setObjectName(QStringLiteral("landscape_textures"));
        m_texture01Btn = new QPushButton(landscape_textures);
        m_texture01Btn->setObjectName(QStringLiteral("m_texture01Btn"));
        m_texture01Btn->setGeometry(QRect(142, 40, 91, 32));
        m_texture01Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label = new QLabel(landscape_textures);
        m_texture01Label->setObjectName(QStringLiteral("m_texture01Label"));
        m_texture01Label->setGeometry(QRect(10, 10, 221, 16));
        m_texture01Label->setFont(font1);
        m_texture01Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Label = new QLabel(landscape_textures);
        m_texture02Label->setObjectName(QStringLiteral("m_texture02Label"));
        m_texture02Label->setGeometry(QRect(10, 180, 221, 16));
        m_texture02Label->setFont(font1);
        m_texture02Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Btn = new QPushButton(landscape_textures);
        m_texture02Btn->setObjectName(QStringLiteral("m_texture02Btn"));
        m_texture02Btn->setGeometry(QRect(142, 210, 91, 32));
        m_texture02Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Label = new QLabel(landscape_textures);
        m_texture03Label->setObjectName(QStringLiteral("m_texture03Label"));
        m_texture03Label->setGeometry(QRect(10, 350, 221, 16));
        m_texture03Label->setFont(font1);
        m_texture03Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Btn = new QPushButton(landscape_textures);
        m_texture03Btn->setObjectName(QStringLiteral("m_texture03Btn"));
        m_texture03Btn->setGeometry(QRect(142, 380, 91, 32));
        m_texture03Btn->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Img = new QLabel(landscape_textures);
        m_texture01Img->setObjectName(QStringLiteral("m_texture01Img"));
        m_texture01Img->setGeometry(QRect(10, 40, 128, 128));
        m_texture01Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture02Img = new QLabel(landscape_textures);
        m_texture02Img->setObjectName(QStringLiteral("m_texture02Img"));
        m_texture02Img->setGeometry(QRect(10, 210, 128, 128));
        m_texture02Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture03Img = new QLabel(landscape_textures);
        m_texture03Img->setObjectName(QStringLiteral("m_texture03Img"));
        m_texture03Img->setGeometry(QRect(10, 380, 128, 128));
        m_texture03Img->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling01SpinBox = new QSpinBox(landscape_textures);
        m_textureTilling01SpinBox->setObjectName(QStringLiteral("m_textureTilling01SpinBox"));
        m_textureTilling01SpinBox->setGeometry(QRect(150, 100, 91, 24));
        m_textureTilling01SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling01SpinBox->setMinimum(1);
        m_textureTilling01SpinBox->setMaximum(128);
        m_textureTilling01Label = new QLabel(landscape_textures);
        m_textureTilling01Label->setObjectName(QStringLiteral("m_textureTilling01Label"));
        m_textureTilling01Label->setGeometry(QRect(150, 80, 91, 20));
        m_textureTilling01Label->setFont(font1);
        m_textureTilling01Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02Label = new QLabel(landscape_textures);
        m_textureTilling02Label->setObjectName(QStringLiteral("m_textureTilling02Label"));
        m_textureTilling02Label->setGeometry(QRect(150, 250, 91, 20));
        m_textureTilling02Label->setFont(font1);
        m_textureTilling02Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02SpinBox = new QSpinBox(landscape_textures);
        m_textureTilling02SpinBox->setObjectName(QStringLiteral("m_textureTilling02SpinBox"));
        m_textureTilling02SpinBox->setGeometry(QRect(150, 270, 91, 24));
        m_textureTilling02SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling02SpinBox->setMinimum(1);
        m_textureTilling02SpinBox->setMaximum(128);
        m_textureTilling03Label = new QLabel(landscape_textures);
        m_textureTilling03Label->setObjectName(QStringLiteral("m_textureTilling03Label"));
        m_textureTilling03Label->setGeometry(QRect(150, 420, 91, 20));
        m_textureTilling03Label->setFont(font1);
        m_textureTilling03Label->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling03SpinBox = new QSpinBox(landscape_textures);
        m_textureTilling03SpinBox->setObjectName(QStringLiteral("m_textureTilling03SpinBox"));
        m_textureTilling03SpinBox->setGeometry(QRect(150, 440, 91, 24));
        m_textureTilling03SpinBox->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_textureTilling03SpinBox->setMinimum(1);
        m_textureTilling03SpinBox->setMaximum(128);
        m_landscapePropertiesTab->addTab(landscape_textures, QString());
        models = new QWidget();
        models->setObjectName(QStringLiteral("models"));
        m_modelsOpenGLView = new QWidget(models);
        m_modelsOpenGLView->setObjectName(QStringLiteral("m_modelsOpenGLView"));
        m_modelsOpenGLView->setGeometry(QRect(13, 10, 300, 300));
        m_modelsOpenGLView->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_landscapePropertiesTab->addTab(models, QString());
        m_oglWindow = new QWidget(sceneTab);
        m_oglWindow->setObjectName(QStringLiteral("m_oglWindow"));
        m_oglWindow->setGeometry(QRect(0, 0, 930, 756));
        m_oglWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_mainMenuTabs->addTab(sceneTab, QString());
        gameObjectTab = new QWidget();
        gameObjectTab->setObjectName(QStringLiteral("gameObjectTab"));
        m_gameObjectGLWindow = new QWidget(gameObjectTab);
        m_gameObjectGLWindow->setObjectName(QStringLiteral("m_gameObjectGLWindow"));
        m_gameObjectGLWindow->setGeometry(QRect(0, 0, 930, 756));
        m_gameObjectGLWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        m_goeSettingsTab = new QTabWidget(gameObjectTab);
        m_goeSettingsTab->setObjectName(QStringLiteral("m_goeSettingsTab"));
        m_goeSettingsTab->setGeometry(QRect(930, -4, 351, 760));
        QFont font3;
        font3.setFamily(QStringLiteral("Menlo"));
        m_goeSettingsTab->setFont(font3);
        m_goeSettingsTab->setTabPosition(QTabWidget::West);
        m_goeSettingsTab->setDocumentMode(true);
        m_goeSettingsTab->setMovable(true);
        m_goeMainSettingTab = new QWidget();
        m_goeMainSettingTab->setObjectName(QStringLiteral("m_goeMainSettingTab"));
        m_createGameObjectConfiguration = new QPushButton(m_goeMainSettingTab);
        m_createGameObjectConfiguration->setObjectName(QStringLiteral("m_createGameObjectConfiguration"));
        m_createGameObjectConfiguration->setGeometry(QRect(20, 20, 281, 32));
        m_goeSettingsTab->addTab(m_goeMainSettingTab, QString());
        m_goeMaterialsSettingTab = new QWidget();
        m_goeMaterialsSettingTab->setObjectName(QStringLiteral("m_goeMaterialsSettingTab"));
        m_materialsComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_materialsComboBox->setObjectName(QStringLiteral("m_materialsComboBox"));
        m_materialsComboBox->setGeometry(QRect(20, 20, 280, 26));
        m_cullFaceCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_cullFaceCheckBox->setObjectName(QStringLiteral("m_cullFaceCheckBox"));
        m_cullFaceCheckBox->setGeometry(QRect(20, 50, 271, 20));
        m_cullModeComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_cullModeComboBox->setObjectName(QStringLiteral("m_cullModeComboBox"));
        m_cullModeComboBox->setGeometry(QRect(118, 76, 182, 26));
        m_depthTestCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_depthTestCheckBox->setObjectName(QStringLiteral("m_depthTestCheckBox"));
        m_depthTestCheckBox->setGeometry(QRect(20, 110, 271, 20));
        m_depthMaskCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_depthMaskCheckBox->setObjectName(QStringLiteral("m_depthMaskCheckBox"));
        m_depthMaskCheckBox->setGeometry(QRect(20, 130, 271, 20));
        m_blendingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_blendingCheckBox->setObjectName(QStringLiteral("m_blendingCheckBox"));
        m_blendingCheckBox->setGeometry(QRect(20, 150, 271, 20));
        m_blendingSourceComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_blendingSourceComboBox->setObjectName(QStringLiteral("m_blendingSourceComboBox"));
        m_blendingSourceComboBox->setGeometry(QRect(118, 176, 182, 26));
        m_blendingDesinationComboBox = new QComboBox(m_goeMaterialsSettingTab);
        m_blendingDesinationComboBox->setObjectName(QStringLiteral("m_blendingDesinationComboBox"));
        m_blendingDesinationComboBox->setGeometry(QRect(118, 206, 182, 26));
        label_7 = new QLabel(m_goeMaterialsSettingTab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(22, 80, 62, 16));
        label_8 = new QLabel(m_goeMaterialsSettingTab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(22, 180, 62, 16));
        label_9 = new QLabel(m_goeMaterialsSettingTab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 210, 91, 16));
        m_clippingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_clippingCheckBox->setObjectName(QStringLiteral("m_clippingCheckBox"));
        m_clippingCheckBox->setGeometry(QRect(20, 240, 271, 20));
        m_clippingXSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingXSpinBox->setObjectName(QStringLiteral("m_clippingXSpinBox"));
        m_clippingXSpinBox->setGeometry(QRect(40, 267, 70, 24));
        m_clippingXSpinBox->setMinimum(-1);
        m_clippingXSpinBox->setMaximum(1);
        m_clippingXSpinBox->setSingleStep(0.1);
        m_clippingYSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingYSpinBox->setObjectName(QStringLiteral("m_clippingYSpinBox"));
        m_clippingYSpinBox->setGeometry(QRect(136, 267, 70, 24));
        m_clippingYSpinBox->setMinimum(-1);
        m_clippingYSpinBox->setMaximum(1);
        m_clippingYSpinBox->setSingleStep(0.1);
        m_clippingZSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingZSpinBox->setObjectName(QStringLiteral("m_clippingZSpinBox"));
        m_clippingZSpinBox->setGeometry(QRect(230, 267, 70, 24));
        m_clippingZSpinBox->setMinimum(-1);
        m_clippingZSpinBox->setMaximum(1);
        m_clippingZSpinBox->setSingleStep(0.1);
        m_clippingWSpinBox = new QDoubleSpinBox(m_goeMaterialsSettingTab);
        m_clippingWSpinBox->setObjectName(QStringLiteral("m_clippingWSpinBox"));
        m_clippingWSpinBox->setGeometry(QRect(136, 297, 70, 24));
        m_clippingWSpinBox->setMinimum(-1024);
        m_clippingWSpinBox->setMaximum(1024);
        m_clippingWSpinBox->setSingleStep(0.1);
        label_10 = new QLabel(m_goeMaterialsSettingTab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(22, 270, 18, 16));
        label_11 = new QLabel(m_goeMaterialsSettingTab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(120, 270, 18, 16));
        label_12 = new QLabel(m_goeMaterialsSettingTab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(214, 270, 18, 16));
        label_13 = new QLabel(m_goeMaterialsSettingTab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(120, 300, 18, 16));
        m_reflectingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_reflectingCheckBox->setObjectName(QStringLiteral("m_reflectingCheckBox"));
        m_reflectingCheckBox->setGeometry(QRect(20, 330, 271, 20));
        m_shadowingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_shadowingCheckBox->setObjectName(QStringLiteral("m_shadowingCheckBox"));
        m_shadowingCheckBox->setGeometry(QRect(20, 350, 271, 20));
        m_debuggingCheckBox = new QCheckBox(m_goeMaterialsSettingTab);
        m_debuggingCheckBox->setObjectName(QStringLiteral("m_debuggingCheckBox"));
        m_debuggingCheckBox->setGeometry(QRect(20, 370, 271, 20));
        m_shaderButton = new QPushButton(m_goeMaterialsSettingTab);
        m_shaderButton->setObjectName(QStringLiteral("m_shaderButton"));
        m_shaderButton->setGeometry(QRect(13, 400, 291, 24));
        m_texture1LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture1LoadButton->setObjectName(QStringLiteral("m_texture1LoadButton"));
        m_texture1LoadButton->setGeometry(QRect(20, 560, 96, 24));
        m_texture1LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_2 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_2->setObjectName(QStringLiteral("m_texture01Label_2"));
        m_texture01Label_2->setGeometry(QRect(10, 440, 111, 16));
        m_texture01Label_2->setFont(font1);
        m_texture01Label_2->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture1Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture1Image->setObjectName(QStringLiteral("m_texture1Image"));
        m_texture1Image->setGeometry(QRect(20, 460, 96, 96));
        m_texture1Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture01Label_3 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_3->setObjectName(QStringLiteral("m_texture01Label_3"));
        m_texture01Label_3->setGeometry(QRect(190, 440, 111, 16));
        m_texture01Label_3->setFont(font1);
        m_texture01Label_3->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture2Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture2Image->setObjectName(QStringLiteral("m_texture2Image"));
        m_texture2Image->setGeometry(QRect(200, 460, 96, 96));
        m_texture2Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture2LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture2LoadButton->setObjectName(QStringLiteral("m_texture2LoadButton"));
        m_texture2LoadButton->setGeometry(QRect(200, 560, 96, 24));
        m_texture2LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture01Label_4 = new QLabel(m_goeMaterialsSettingTab);
        m_texture01Label_4->setObjectName(QStringLiteral("m_texture01Label_4"));
        m_texture01Label_4->setGeometry(QRect(10, 600, 81, 16));
        m_texture01Label_4->setFont(font1);
        m_texture01Label_4->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_texture3Image = new QLabel(m_goeMaterialsSettingTab);
        m_texture3Image->setObjectName(QStringLiteral("m_texture3Image"));
        m_texture3Image->setGeometry(QRect(20, 620, 96, 96));
        m_texture3Image->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);"));
        m_texture3LoadButton = new QPushButton(m_goeMaterialsSettingTab);
        m_texture3LoadButton->setObjectName(QStringLiteral("m_texture3LoadButton"));
        m_texture3LoadButton->setGeometry(QRect(20, 720, 96, 24));
        m_texture3LoadButton->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        m_goeSettingsTab->addTab(m_goeMaterialsSettingTab, QString());
        m_goeAnimationsSettingTab = new QWidget();
        m_goeAnimationsSettingTab->setObjectName(QStringLiteral("m_goeAnimationsSettingTab"));
        m_goeSettingsTab->addTab(m_goeAnimationsSettingTab, QString());
        m_mainMenuTabs->addTab(gameObjectTab, QString());
        CMainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(CMainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1280, 22));
        CMainWindow->setMenuBar(menuBar);

        retranslateUi(CMainWindow);

        m_mainMenuTabs->setCurrentIndex(0);
        m_landscapePropertiesTab->setCurrentIndex(0);
        m_goeSettingsTab->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(CMainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *CMainWindow)
    {
        CMainWindow->setWindowTitle(QApplication::translate("CMainWindow", "indieEngine3D MapEditor", 0));
        generateGroupBox->setTitle(QApplication::translate("CMainWindow", "Generate", 0));
        label->setText(QApplication::translate("CMainWindow", "Frequency[0.1 .. 64.0]:", 0));
        label_2->setText(QApplication::translate("CMainWindow", "Octaves[1 .. 16]:", 0));
        label_3->setText(QApplication::translate("CMainWindow", "Seed:", 0));
        generateButton->setText(QApplication::translate("CMainWindow", "Generate", 0));
        label_4->setText(QApplication::translate("CMainWindow", "Size[64 .. 512]:", 0));
        label_5->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_6->setText(QApplication::translate("CMainWindow", "y:", 0));
        editGroupBox->setTitle(QApplication::translate("CMainWindow", "Edit", 0));
        m_falloffLabel->setText(QApplication::translate("CMainWindow", "Falloff Coefficient:", 0));
        m_brushSizeLabel->setText(QApplication::translate("CMainWindow", "Brush Size:", 0));
        m_smoothLabel->setText(QApplication::translate("CMainWindow", "Smooth Coefficient:", 0));
        m_brushStrengthLabel->setText(QApplication::translate("CMainWindow", "Brush Strength:", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(landscape_heightmap), QApplication::translate("CMainWindow", "Landscape", 0));
        m_texture01Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture01Label->setText(QApplication::translate("CMainWindow", "Texture sampler 1:", 0));
        m_texture02Label->setText(QApplication::translate("CMainWindow", "Texture sampler 2:", 0));
        m_texture02Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture03Label->setText(QApplication::translate("CMainWindow", "Texture sampler 3:", 0));
        m_texture03Btn->setText(QApplication::translate("CMainWindow", "Open...", 0));
        m_texture01Img->setText(QString());
        m_texture02Img->setText(QString());
        m_texture03Img->setText(QString());
        m_textureTilling01Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_textureTilling02Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_textureTilling03Label->setText(QApplication::translate("CMainWindow", "Tilling:", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(landscape_textures), QApplication::translate("CMainWindow", "Textures", 0));
        m_landscapePropertiesTab->setTabText(m_landscapePropertiesTab->indexOf(models), QApplication::translate("CMainWindow", "Models", 0));
        m_mainMenuTabs->setTabText(m_mainMenuTabs->indexOf(sceneTab), QApplication::translate("CMainWindow", "Scene", 0));
        m_createGameObjectConfiguration->setText(QApplication::translate("CMainWindow", "Create configuration...", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeMainSettingTab), QApplication::translate("CMainWindow", "Configuration", 0));
        m_cullFaceCheckBox->setText(QApplication::translate("CMainWindow", "  Cull Face", 0));
        m_depthTestCheckBox->setText(QApplication::translate("CMainWindow", "  Depth Test", 0));
        m_depthMaskCheckBox->setText(QApplication::translate("CMainWindow", "  Depth Mask", 0));
        m_blendingCheckBox->setText(QApplication::translate("CMainWindow", "  Blending", 0));
        label_7->setText(QApplication::translate("CMainWindow", "Mode:", 0));
        label_8->setText(QApplication::translate("CMainWindow", "Source:", 0));
        label_9->setText(QApplication::translate("CMainWindow", "Destination:", 0));
        m_clippingCheckBox->setText(QApplication::translate("CMainWindow", "  Clipping", 0));
        label_10->setText(QApplication::translate("CMainWindow", "x:", 0));
        label_11->setText(QApplication::translate("CMainWindow", "y:", 0));
        label_12->setText(QApplication::translate("CMainWindow", "z:", 0));
        label_13->setText(QApplication::translate("CMainWindow", "w:", 0));
        m_reflectingCheckBox->setText(QApplication::translate("CMainWindow", "  Reflecting", 0));
        m_shadowingCheckBox->setText(QApplication::translate("CMainWindow", "  Shadowing", 0));
        m_debuggingCheckBox->setText(QApplication::translate("CMainWindow", "  Debugging", 0));
        m_shaderButton->setText(QApplication::translate("CMainWindow", "Shader...", 0));
        m_texture1LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_2->setText(QApplication::translate("CMainWindow", "Texture 1:", 0));
        m_texture1Image->setText(QString());
        m_texture01Label_3->setText(QApplication::translate("CMainWindow", "Texture 2:", 0));
        m_texture2Image->setText(QString());
        m_texture2LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_texture01Label_4->setText(QApplication::translate("CMainWindow", "Texture 3:", 0));
        m_texture3Image->setText(QString());
        m_texture3LoadButton->setText(QApplication::translate("CMainWindow", "Load...", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeMaterialsSettingTab), QApplication::translate("CMainWindow", "Materials", 0));
        m_goeSettingsTab->setTabText(m_goeSettingsTab->indexOf(m_goeAnimationsSettingTab), QApplication::translate("CMainWindow", "Animations", 0));
        m_mainMenuTabs->setTabText(m_mainMenuTabs->indexOf(gameObjectTab), QApplication::translate("CMainWindow", "Game Object", 0));
    } // retranslateUi

};

namespace Ui {
    class CMainWindow: public Ui_CMainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CMAINWINDOW_H
